Repository ExtremeFLOW/neko, pull requests merged in 2022-03, with the labels that each got.

#419 Add missing deps.
  src/.depends
Labels: bug

#420 Fix HIP kernels in single precision
  src/gs/bcknd/device/hip/gs_kernels.h
  src/krylov/bcknd/device/hip/pc_jacobi.hip
Labels: bug, GPU

#421 Exit makeneko non-zero if compilation failed
  makeneko.in
Labels: enhancement

#424 Use log interface in I/O routines
  src/.depends
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/io/rea_file.f90
  src/io/vtk_file.f90
Labels: enhancement

#423 Labeled facet
  doc/pages/case-file.md
  src/bc/bc.f90
  src/comm/mpi_types.f90
  src/common/parameters.f90
  src/fluid/fluid_method.f90
  src/fluid/fluid_pnpn.f90
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/krylov/pc_hsmg.f90
  src/mesh/mesh.f90
Labels: enhancement

#425 Ignore skrufs files in doc/Makefile.am
  doc/Makefile.am
Labels: documentation, enhancement

#427 Fix ICE with CCE
  src/bc/bc.f90
  src/fluid/fluid_method.f90
  src/fluid/fluid_pnpn.f90
  src/io/nmsh_file.f90
  src/mesh/mesh.f90
Labels: bug, compilers, Cray

#429 Use gs_op interface for most gather-scatter operations
  src/fluid/flow_ic.f90
  src/gs/gather_scatter.f90
  src/krylov/bcknd/cpu/pc_jacobi.f90
  src/krylov/bcknd/device/pc_jacobi_device.F90
  src/krylov/bcknd/sx/pc_jacobi_sx.f90
  src/krylov/pc_hsmg.f90
  src/math/fdm.f90
  src/math/schwarz.f90
  src/sem/coef.f90
Labels: enhancement

#431 Dirichlet velocity
  src/fluid/fluid_method.f90
  src/fluid/fluid_pnpn.f90
Labels: bug, enhancement

#434 Fix possible race
  src/math/bcknd/device/cuda/schwarz_kernel.h
  src/math/bcknd/device/hip/schwarz_kernel.h
Labels: bug, GPU

#435 Remove redundant memset op. (left over from older gs-kernel design)
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/hip/gs.hip
  src/gs/bcknd/device/opencl/gs.c
Labels: enhancement, GPU

#432 User inflow device
  src/.depends
  src/Makefile.am
  src/bc/bcknd/device/cuda/inhom_dirichlet.cu
  src/bc/bcknd/device/cuda/inhom_dirichlet_kernel.h
  src/bc/bcknd/device/device_inhom_dirichlet.F90
  src/bc/bcknd/device/hip/inhom_dirichlet.hip
  src/bc/bcknd/device/hip/inhom_dirichlet_kernel.h
  src/bc/bcknd/device/opencl/inhom_dirichlet.c
  src/bc/bcknd/device/opencl/inhom_dirichlet_kernel.cl
  src/bc/blasius.f90
  src/bc/usr_inflow.f90
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
Labels: GPU

#437 Improvements to the source term
  src/case.f90
  src/common/source.f90
  src/common/user_intf.f90
  src/fluid/fluid_method.f90
  src/math/math.f90
Labels: enhancement, GPU

#438 Make communication method in gs abstract
  src/.depends
  src/Makefile.am
  src/gs/gather_scatter.f90
  src/gs/gs_comm.f90
  src/gs/gs_mpi.f90
Labels: enhancement, GPU

#439 User deform mesh
  src/common/utils.f90
  src/mesh/mesh.f90
  src/sem/dofmap.f90
Labels: enhancement

#442 Add initialize modules func for user
  src/common/user_intf.f90
  src/simulation.f90
Labels: enhancement

#443 Move send/recv dof to shared-gs order to gs_comm
  src/gs/gather_scatter.f90
  src/gs/gs_comm.f90
  src/gs/gs_mpi.f90
Labels: enhancement

#440 Velocity projection
  bench/tgv32/tgv.case
  examples/tgv/tgv.case
  src/comm/mpi_types.f90
  src/common/parameters.f90
  src/fluid/fluid_plan4.f90
  src/fluid/fluid_pnpn.f90
  src/mesh/mesh.f90
Labels: enhancement

#444 Fix invalid type in mpi derived type
  src/comm/mpi_types.f90
Labels: bug

#446 Fix fld files cycle counter
  src/io/fld_file.f90
Labels: bug

#447 GPU direct MPI in gather scatter
  reframe/settings.py
  reframe/src/tgv.case.template
  src/.depends
  src/Makefile.am
  src/device/device.F90
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/cuda/gs_kernels.h
  src/gs/bcknd/device/device_mpi.c
  src/gs/bcknd/device/gs_device.F90
  src/gs/bcknd/device/gs_device_mpi.F90
  src/gs/bcknd/device/hip/gs.hip
  src/gs/bcknd/device/hip/gs_kernels.h
  src/gs/gather_scatter.f90
  src/gs/gs_comm.f90
  src/gs/gs_mpi.f90
  src/sem/dofmap.f90
Labels: enhancement, GPU

#448 Fix invalid kernel launches at scale
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/hip/gs.hip
Labels: bug, GPU

#450 Make device aware MPI optional
  configure.ac
  src/config/neko_config.f90.in
  src/gs/bcknd/device/gs_device.F90
  src/gs/gather_scatter.f90
Labels: enhancement, GPU

#449 Make application of vel bc more reasonable
  src/fluid/fluid_method.f90
  src/fluid/fluid_pnpn.f90
Labels: enhancement

#451 Backport CUDA/HIP race fixes to OpenCL kernel
  src/math/bcknd/device/opencl/schwarz_kernel.cl
Labels: bug, GPU

#452 Improve utilization in gs_pack_kernel
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/cuda/gs_kernels.h
  src/gs/bcknd/device/gs_device_mpi.F90
  src/gs/bcknd/device/hip/gs.hip
  src/gs/bcknd/device/hip/gs_kernels.h
Labels: enhancement, GPU

#456 Change 8 to 12
  src/io/re2_file.f90
Labels: bug, enhancement

#458 Add sync in device MPI nbwait
  src/gs/bcknd/device/gs_device_mpi.F90
Labels: bug, GPU

#459 Fix chkp restart with device backend
  src/.depends
  src/common/checkpoint.f90
  src/io/chkp_output.f90
  src/simulation.f90
Labels: enhancement, GPU
