Repository ExtremeFLOW/neko, pull requests merged in 2022-05, with the labels that each got.

#484 Fix various issues with dependency tracking
  src/.depends
  src/.depends_device
  src/Makefile.am
Labels: enhancement, compilers

#485 Disable preprocessing in doxygen
  doc/Doxyfile.in
Labels: documentation

#486 Add more valid prog env.
  reframe/checks.py
Labels: enhancement

#489 Fix OpenCL detection on none Apple platforms
  m4/ax_opencl.m4
Labels: enhancement, GPU

#490 Don't assume rp corresponds to byte size
  src/common/projection.f90
  src/fluid/fluid_method.f90
  src/gs/bcknd/device/gs_device_mpi.F90
Labels: bug, compilers, GPU

#491 Ensure CFL calculation is done on selected backend
  src/.depends_device
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/math/bcknd/cpu/opr_cpu.f90
  src/math/bcknd/device/cuda/cfl_kernel.h
  src/math/bcknd/device/cuda/opr_cfl.cu
  src/math/bcknd/device/hip/cfl_kernel.h
  src/math/bcknd/device/hip/opr_cfl.hip
  src/math/bcknd/device/opencl/cfl_kernel.cl
  src/math/bcknd/device/opencl/opr_cfl.c
  src/math/bcknd/device/opr_device.F90
  src/math/operators.f90
Labels: enhancement, GPU

#492 Increase vector length during CFL calculation on SX
  src/.depends
  src/Makefile.am
  src/math/bcknd/sx/opr_sx.f90
  src/math/bcknd/sx/sx_cfl.f90
  src/math/operators.f90
Labels: enhancement, SX

#493 Fix compiler issues in BC for NEC and NAG
  src/bc/bc.f90
Labels: bug, compilers, SX

#494 Feature/dong outflow
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/bc/bc.f90
  src/bc/bcknd/device/cuda/dong_outflow.cu
  src/bc/bcknd/device/cuda/dong_outflow_kernel.h
  src/bc/bcknd/device/device_dong_outflow.F90
  src/bc/bcknd/device/hip/dong_outflow.hip
  src/bc/bcknd/device/hip/dong_outflow_kernel.h
  src/bc/dong_outflow.f90
  src/comm/mpi_types.f90
  src/common/parameters.f90
  src/fluid/fluid_method.f90
  src/fluid/fluid_pnpn.f90
  src/krylov/pc_hsmg.f90
  src/sem/coef.f90
Labels: enhancement, GPU

#495 Fix dong build when using HIP
  src/bc/bcknd/device/hip/dong_outflow.hip
Labels: bug, compilers, GPU

#499 Add missing OpenCL implementation for Dong outflow
  src/.depends_device
  src/Makefile.am
  src/bc/bcknd/device/device_dong_outflow.F90
  src/bc/bcknd/device/opencl/dong_outflow.c
  src/bc/bcknd/device/opencl/dong_outflow_kernel.cl
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
Labels: enhancement, GPU

#500 Offload (most of) coef. calc. to device
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/hip/math_kernel.h
  src/sem/bcknd/device/cuda/coef.cu
  src/sem/bcknd/device/cuda/coef_kernel.h
  src/sem/bcknd/device/device_coef.F90
  src/sem/bcknd/device/hip/coef.hip
  src/sem/bcknd/device/hip/coef_kernel.h
  src/sem/bcknd/device/opencl/coef.c
  src/sem/bcknd/device/opencl/coef_kernel.cl
  src/sem/coef.f90
  src/sem/dofmap.f90
Labels: enhancement, GPU

#501 Temp. disable HIP backend for dxyzdrst kernel
  src/sem/coef.f90
Labels: bug, GPU

#502 Make linter stricter
  .github/workflows/lint.yml
  src/fluid/advection.f90
  src/fluid/flow_ic.f90
  src/fluid/fluid_abbdf.f90
  src/math/fast3d.f90
  src/math/mathops.f90
  src/math/schwarz.f90
  src/mesh/mesh.f90
  src/sem/dofmap.f90
Labels: enhancement

#503 Add code style guideline to doxygen documentation
  doc/pages/code-style.md
Labels: documentation

#505 Add a description of the device layer to the documentation
  doc/pages/accelerators.md
Labels: documentation, GPU

#507 data compression development
  src/.depends
  src/Makefile.am
  src/sem/cpr.f90
Labels: enhancement

#510 Make the linter happy
  src/krylov/bcknd/sx/pc_jacobi_sx.f90
Labels: enhancement

#512 Dont assume local .ne. shared during gs operations
  src/gs/bcknd/cpu/gs_cpu.f90
  src/gs/bcknd/device/gs_device.F90
  src/gs/bcknd/sx/gs_sx.f90
  src/gs/gather_scatter.f90
  src/gs/gs_bcknd.f90
Labels: bug, SX, GPU

#513 Add device glsum
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  tests/device_math/device_math_parallel.pf
Labels: enhancement, GPU

#514 Move more coef computations over to the device
  src/sem/coef.f90
Labels: GPU

#509 Fix/bcs
  src/bc/non_normal.f90
  src/bc/symmetry.f90
  src/fluid/fluid_pnpn.f90
Labels: bug

#515 New device MPI
  cuda.mk
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/cuda/gs_kernels.h
  src/gs/bcknd/device/device_mpi.c
  src/gs/bcknd/device/gs_device.F90
  src/gs/bcknd/device/gs_device_mpi.F90
  src/gs/bcknd/device/hip/gs.hip
  src/gs/bcknd/device/hip/gs_kernels.h
  src/gs/gather_scatter.f90
Labels: GPU

#516 proj_log
  src/common/projection.f90
  src/fluid/fluid_pnpn.f90
Labels: enhancement

#517 Add external style to Doxygen
  .github/workflows/documentation.yml
  doc/Doxyfile.in
Labels: documentation

#520 Add option to select CUDA flags via configure
  configure.ac
  cuda.mk
  m4/ax_cuda.m4
  src/Makefile.am
  src/gs/bcknd/device/cuda/gs_kernels.h
Labels: GPU, NVIDIA

#521 Add option to select HIP flags via configure
  configure.ac
  hip.mk
  m4/ax_hip.m4
  src/Makefile.am
Labels: GPU, AMD

#522 Fix invalid indicies
  src/sem/bcknd/device/cuda/coef_kernel.h
  src/sem/bcknd/device/hip/coef_kernel.h
Labels: bug, GPU, NVIDIA, AMD

#523 Disable the dofmap's final proc., fixes coef calc. w. HIP
  src/sem/coef.f90
  src/sem/dofmap.f90
Labels: bug, compilers, GPU, AMD

#528 Fix invalid parameter
  examples/turbpipe/pipe.case
  examples/turbpipe/pipe_device.case
Labels: bug

#530 Make gs more safe for CCE (avoid %array() operator)
  src/gs/gather_scatter.f90
Labels: bug, compilers, Cray

#532 Fix find_blks
  src/gs/gather_scatter.f90
Labels: bug
