Repository ExtremeFLOW/neko, pull requests merged in 2022-02, with the labels that each got.

#377 Add CUDA CI
  .github/workflows/develop.yml
  src/math/bcknd/device/device_math.F90
Labels: GPU

#378 Fix invalid doxygen/latex tags
  src/fluid/flow_profile.f90
Labels: documentation

#379 Don't assume ptrs are 0 or NULL...
  src/krylov/bcknd/device/cuda/gmres_aux.cu
  src/krylov/bcknd/device/cuda/pipecg_aux.cu
  src/krylov/bcknd/device/hip/gmres_aux.hip
  src/krylov/bcknd/device/hip/pipecg_aux.hip
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/opencl/math.c
Labels: bug, GPU

#381 Throw a hard error for unsupported values of lx in the CUDA/HIP backend
  src/math/bcknd/device/cuda/ax_helm.cu
  src/math/bcknd/device/cuda/opr_cdtp.cu
  src/math/bcknd/device/cuda/opr_conv1.cu
  src/math/bcknd/device/cuda/opr_dudxyz.cu
  src/math/bcknd/device/cuda/opr_opgrad.cu
  src/math/bcknd/device/hip/ax_helm.hip
  src/math/bcknd/device/hip/opr_cdtp.hip
  src/math/bcknd/device/hip/opr_conv1.hip
  src/math/bcknd/device/hip/opr_dudxyz.hip
  src/math/bcknd/device/hip/opr_opgrad.hip
Labels: bug, enhancement, GPU

#383 Add documentation pages
  README.md
  doc/Doxyfile.in
  doc/Makefile.am
  doc/pages/case-file.md
  doc/pages/index.md
  doc/pages/publication-list.md
Labels: documentation, enhancement

#385 Fix dealiasing issues with SX-Aurora backend
  src/fluid/advection.f90
Labels: bug, SX

#386 Fix issues due to dealiasing in xsmm backend
  src/fluid/advection.f90
  src/math/bcknd/xsmm/opr_xsmm.F90
Labels: bug

#387 Output max sample time instead of rank zero time
  src/common/sampler.f90
Labels: bug, enhancement

#391 Initialize p in CG
  src/krylov/bcknd/cpu/cg.f90
Labels: bug

#393 Quality of life fixes
  src/.depends
  src/math/bcknd/device/tensor_device.F90
Labels: enhancement

#394 Add CUDA kernels for abbdf
  src/.depends
  src/Makefile.am
  src/fluid/bcknd/device/cuda/fluid_abbdf_cuda.cu
  src/fluid/bcknd/device/cuda/makeabf_kernel.h
  src/fluid/bcknd/device/cuda/makebdf_kernel.h
  src/fluid/bcknd/device/cuda/sumab_kernel.h
  src/fluid/bcknd/device/fluid_abbdf_device.F90
  src/fluid/fluid_abbdf_fctry.f90
Labels: GPU

#395 Quality of life CI (now tests several backends, compilers and OS)
  .github/workflows/develop.yml
Labels: enhancement

#397 Change to combined mathop call
  src/fluid/bcknd/device/device_fluid_plan4.f90
Labels: enhancement, GPU

#398 Add CUDA backend for residual calculations in new solver formulation
  src/.depends
  src/Makefile.am
  src/fluid/bcknd/device/cuda/pnpn_res_cuda.cu
  src/fluid/bcknd/device/cuda/prs_res_kernel.h
  src/fluid/bcknd/device/cuda/vel_res_update_kernel.h
  src/fluid/bcknd/device/fluid_abbdf_device.F90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/fluid_pnpn.f90
  src/fluid/pnpn_res_fctry.f90
Labels: enhancement, GPU

#399 Fix build deps.
  src/.depends
Labels: bug

#400 More error messages, aid in fixing #200,#237
  src/adt/htable.f90
Labels: bug, enhancement, compilers

#401 Add more error messages in stack to catch flaky llvm based Fortran compilers (X_X)
  src/adt/stack.f90
Labels: bug, enhancement, compilers

#402 Fix runtime issues caused by flaky LLVM based compilers
  src/adt/htable.f90
  src/adt/uset.f90
  src/mesh/mesh.f90
Labels: bug, compilers

#403 Fix invalid makeabf argument on device
  src/fluid/bcknd/device/fluid_abbdf_device.F90
Labels: bug, GPU

#404 Fix horrible bug in makebdf's CUDA kernel
  src/fluid/bcknd/device/cuda/fluid_abbdf_cuda.cu
Labels: bug, GPU

#405 Add HIP backend for the new solver (and rename CUDA files to be consistent
  src/.depends
  src/Makefile.am
  src/fluid/bcknd/device/cuda/fluid_abbdf.cu
  src/fluid/bcknd/device/cuda/pnpn_res.cu
  src/fluid/bcknd/device/fluid_abbdf_device.F90
  src/fluid/bcknd/device/hip/fluid_abbdf.hip
  src/fluid/bcknd/device/hip/fluid_abbdf_hip.hip
  src/fluid/bcknd/device/hip/makeabf_kernel.h
  src/fluid/bcknd/device/hip/makebdf_kernel.h
  src/fluid/bcknd/device/hip/pnpn_res.hip
  src/fluid/bcknd/device/hip/prs_res_kernel.h
  src/fluid/bcknd/device/hip/sumab_kernel.h
  src/fluid/bcknd/device/hip/vel_res_update_kernel.h
  src/fluid/bcknd/device/pnpn_res_device.F90
Labels: GPU

#407 Fix typo, use template parameter in fluid kernels
  src/fluid/bcknd/device/cuda/makeabf_kernel.h
  src/fluid/bcknd/device/cuda/makebdf_kernel.h
  src/fluid/bcknd/device/cuda/prs_res_kernel.h
  src/fluid/bcknd/device/cuda/sumab_kernel.h
  src/fluid/bcknd/device/cuda/vel_res_update_kernel.h
  src/fluid/bcknd/device/hip/makeabf_kernel.h
  src/fluid/bcknd/device/hip/makebdf_kernel.h
  src/fluid/bcknd/device/hip/prs_res_kernel.h
  src/fluid/bcknd/device/hip/sumab_kernel.h
  src/fluid/bcknd/device/hip/vel_res_update_kernel.h
Labels: bug, GPU

#408 Add OpenCL backend for new pnpn solver
  src/.depends
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/fluid/bcknd/device/fluid_abbdf_device.F90
  src/fluid/bcknd/device/opencl/abbdf_kernel.cl
  src/fluid/bcknd/device/opencl/fluid_abbdf.c
  src/fluid/bcknd/device/opencl/pnpn_res.c
  src/fluid/bcknd/device/opencl/pnpn_res_kernel.cl
  src/fluid/bcknd/device/pnpn_res_device.F90
Labels: GPU

#409 Add bc outlet normal and fix bc bugs
  src/bc/bcknd/device/cuda/facet_normal_kernel.h
  src/bc/bcknd/device/hip/facet_normal_kernel.h
  src/bc/bcknd/device/opencl/facet_normal_kernel.cl
  src/common/utils.f90
  src/fluid/fluid_method.f90
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/krylov/pc_hsmg.f90
  src/mesh/mesh.f90
  src/sem/coef.f90
Labels: bug, enhancement, GPU

#410 Add fdm and tensor kernels for OpenCL
  src/.depends
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/math/bcknd/device/fdm_device.F90
  src/math/bcknd/device/opencl/fdm.c
  src/math/bcknd/device/opencl/fdm_kernel.cl
  src/math/bcknd/device/opencl/tensor.c
  src/math/bcknd/device/opencl/tensor_kernel.cl
  src/math/bcknd/device/tensor_device.F90
Labels: GPU

#413 Add OpenCL kernels for schwarz
  src/.depends
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/krylov/pc_hsmg.f90
  src/math/bcknd/device/cuda/schwarz.cu
  src/math/bcknd/device/device_schwarz.F90
  src/math/bcknd/device/hip/schwarz.hip
  src/math/bcknd/device/opencl/fdm_kernel.cl
  src/math/bcknd/device/opencl/schwarz.c
  src/math/bcknd/device/opencl/schwarz_kernel.cl
  src/math/fdm.f90
  src/math/schwarz.f90
Labels: enhancement, GPU

#414 Cleanup
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
  src/fluid/bcknd/sx/pnpn_res_sx.f90
  src/mesh/mesh.f90
Labels: enhancement

#415 Fix uninitialised pointers
  src/sem/dofmap.f90
Labels: bug

#416 Mark all indexes
  src/bc/symmetry.f90
Labels: bug

#417 Add missing parts of the SX bcknd for new pnpn solver
  src/.depends
  src/Makefile.am
  src/fluid/bcknd/sx/fluid_abbdf_sx.f90
  src/fluid/fluid_abbdf_fctry.f90
Labels: SX

#418 Non normal bc
  src/.depends
  src/Makefile.am
  src/bc/non_normal.f90
  src/fluid/fluid_method.f90
  src/fluid/fluid_pnpn.f90
Labels: enhancement
