Repository ExtremeFLOW/neko, pull requests merged in 2022-12, with the labels that each got.

#733 Use warp shuffle in CFL calculation to reduce data transfer
  src/math/bcknd/device/cuda/cfl_kernel.h
  src/math/bcknd/device/cuda/opr_cfl.cu
  src/math/bcknd/device/hip/cfl_kernel.h
  src/math/bcknd/device/hip/opr_cfl.hip
Labels: enhancement, GPU, AMD

#735 Change to ubuntu 20.04 for linter actions
  .github/workflows/develop.yml
Labels: bug

#734 Periodic BCs needs mesh connectivity
  contrib/prepart/prepart.f90
Labels: bug

#736 Fix dynamic loadbalancing for meshes with labeled zones
  src/comm/redist.f90
Labels: bug

#737 added hip
  src/math/bcknd/device/hip/tensor.hip
  src/math/bcknd/device/hip/tensor_kernel.h
Labels: GPU, AMD

#738 Allow for 10th order polynomials (HIP)
  src/krylov/bcknd/device/hip/pc_jacobi.hip
  src/math/bcknd/device/hip/fdm.hip
  src/math/bcknd/device/hip/opr_cdtp.hip
  src/math/bcknd/device/hip/opr_cfl.hip
  src/math/bcknd/device/hip/opr_conv1.hip
  src/math/bcknd/device/hip/opr_dudxyz.hip
  src/math/bcknd/device/hip/opr_opgrad.hip
  src/math/bcknd/device/hip/schwarz.hip
  src/math/bcknd/device/hip/tensor.hip
Labels: GPU, AMD

#739 Minor macro fix
  src/math/bcknd/device/hip/tensor.hip
Labels: bug, GPU, AMD

#741 Temporarily disable CrayPat regions due to issues with CCE
  src/common/profiler.F90
Labels: bug, Cray

#743 Add log verbosity level
  doc/pages/appendix.md
  src/common/log.f90
Labels: enhancement

#744 Fixed regression in offline tool
  contrib/prepart/prepart.f90
Labels: bug

#747 Reduce comm. during init
  src/gs/gather_scatter.f90
  src/mesh/mesh.f90
Labels: enhancement

#748 Remove redudant memory copies in reductions (if dev. MPI is present)
  configure.ac
  src/Makefile.am
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/opr_cfl.cu
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/device_mpi_reduce.c
  src/math/bcknd/device/device_mpi_reduce.h
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/opr_cfl.hip
  src/math/operators.f90
Labels: enhancement, GPU, NVIDIA, AMD

#749 Fix undefined neigh_order array for pe_size = 1
  src/mesh/mesh.f90
Labels: bug

#750 Fuse kernels and remove redudant HtoD (DtoH) transfers in proj.
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/common/bcknd/device/cuda/projection.cu
  src/common/bcknd/device/cuda/projection_kernel.h
  src/common/bcknd/device/device_projection.F90
  src/common/bcknd/device/hip/projection.hip
  src/common/bcknd/device/hip/projection_kernel.h
  src/common/projection.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/device_mpi_reduce.c
  src/math/bcknd/device/device_mpi_reduce.h
  src/math/bcknd/device/hip/math.hip
Labels: enhancement, GPU, NVIDIA, AMD

#753 Fix issues with gh actions macOS runners
  .github/workflows/develop.yml
Labels: compilers

#752 Fix tnsr3d w. OpenCL bcknd
  src/math/bcknd/device/opencl/tensor.c
  src/math/tensor.f90
Labels: bug, GPU, OpenCL

#754 Fix pFUnit version to 4.4.2
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: CI
