Repository ExtremeFLOW/neko, pull requests merged in 2022-11, with the labels that each got.

#699 Consistent spelling in exposed intf, usr -> user
  bench/tgv32/tgv.f90
  examples/cyl_boundary_layer/cyl_bl.f90
  examples/lid/lid.f90
  examples/rayleigh-benard/rayleigh.f90
  examples/tgv/tgv.f90
  examples/turbpipe/pipe.f90
  reframe/src/tgv.f90
  src/case.f90
  src/common/user_intf.f90
  src/simulation.f90
Labels: enhancement

#701 Add scalar source terms
  examples/rayleigh-benard/rayleigh.case
  src/.depends
  src/case.f90
  src/comm/mpi_types.f90
  src/common/parameters.f90
  src/common/source_scalar.f90
  src/common/user_intf.f90
  src/scalar/scalar_method.f90
  src/simulation.f90
Labels: enhancement

#708 Cleanup device unit tests, use new `DEVICE` macro
  tests/device/device.pf
  tests/device_math/device_math_parallel.pf
  tests/field/field_parallel.pf
  tests/mean_field/mean_field_parallel.pf
  tests/mean_sqr_field/mean_sqr_field_parallel.pf
Labels: enhancement, GPU

#713 Fix ICE with NAG
  src/gs/gs_mpi.f90
  src/io/chkp_file.f90
Labels: bug, compilers, NAG

#714 Add ReFrame tests to integration tests
  .github/workflows/develop.yml
  .github/workflows/main.yml
  reframe/checks.py
  reframe/settings.py
  reframe/src/tgv.case.template
Labels: enhancement

#715 Test scalar features in CI
  .github/workflows/develop.yml
  .github/workflows/main.yml
  reframe/checks.py
  reframe/src/rayleigh.case.template
  reframe/src/rayleigh.f90
Labels: enhancement, compilers

#716 Add user-defined parameters
  doc/pages/case-file.md
  src/comm/mpi_types.f90
  src/common/parameters.f90
Labels: enhancement

#718 Fix reframe tests for rayleigh-benard
  .github/workflows/develop.yml
  reframe/checks.py
  reframe/settings.py
Labels: bug

#719 Fix invalid arguments to rhs maker OpenCL backend
  src/common/bcknd/device/opencl/rhs_maker_kernel.cl
Labels: bug, GPU, OpenCL

#723 Add NVIDIA Fortran to the integration tests
  .github/workflows/develop.yml
  .github/workflows/main.yml
  patches/nvhpc_bge.patch
Labels: compilers, NVIDIA

#724 Feature/template fdm
  src/math/bcknd/device/cuda/fdm.cu
  src/math/bcknd/device/cuda/fdm_kernel.h
  src/math/bcknd/device/hip/fdm.hip
  src/math/bcknd/device/hip/fdm_kernel.h
Labels: GPU, NVIDIA, AMD

#725 Scalar checkpoint
  src/case.f90
  src/common/checkpoint.f90
  src/io/chkp_file.f90
  src/simulation.f90
Labels: enhancement

#726 Larger mesh support
  src/io/nmsh_file.f90
  src/io/re2_file.f90
Labels: bug, enhancement

#727 Feature/shared mem opt shwarz
  src/math/bcknd/device/cuda/schwarz.cu
  src/math/bcknd/device/cuda/schwarz_kernel.h
  src/math/bcknd/device/hip/schwarz.hip
  src/math/bcknd/device/hip/schwarz_kernel.h
Labels: GPU, NVIDIA, AMD

#729 Update documentation
  doc/Doxyfile.in
  doc/pages/appendix.md
  doc/pages/case-file.md
Labels: documentation
