Repository ExtremeFLOW/neko, pull requests merged in 2022-10, with the labels that each got.

#652 Add necessary compiler flags for building with PGI and NVFORTRAN
  configure.ac
Labels: compilers, NVIDIA

#653 Port EuroHack22 optimisations to HIP/OpenCL kernels
  src/fluid/bcknd/device/fluid_abbdf_device.F90
  src/fluid/bcknd/device/hip/fluid_abbdf.hip
  src/fluid/bcknd/device/hip/makeabf_kernel.h
  src/fluid/bcknd/device/hip/makebdf_kernel.h
  src/fluid/bcknd/device/opencl/abbdf_kernel.cl
  src/fluid/bcknd/device/opencl/fluid_abbdf.c
Labels: enhancement, GPU, AMD

#655 Change CUDA glsc3 to use shuffle warp reduce
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
Labels: GPU, NVIDIA

#656 Change all CUDA reductions in (except many variants) to warp shuffle
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
Labels: enhancement, GPU, NVIDIA

#654 Pass down parameters in user_check
  bench/tgv32/tgv.f90
  examples/lid/lid.f90
  examples/lid/lid2d.f90
  examples/tgv/tgv.f90
  src/common/user_intf.f90
  src/simulation.f90
Labels: enhancement

#658 Fix missing template argument
  src/math/bcknd/device/cuda/math.cu
Labels: bug, GPU, NVIDIA

#659 Change to shuffle warp reduce in HIP kernels
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
Labels: enhancement, GPU, AMD

#657 Consitent symmetric vertex notation
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/io/rea_file.f90
  src/io/vtk_file.f90
  src/mesh/hex.f90
  src/mesh/mesh.f90
  src/mesh/quad.f90
  src/sem/dofmap.f90
Labels: don't merge

#663 Profiler interface
  configure.ac
  m4/ax_nvtx.m4
  src/.depends
  src/Makefile.am
  src/common/profiler.F90
  src/device/cuda/nvtx.F90
  src/device/cuda_intf.F90
  src/fluid/fluid_pnpn.f90
  src/gs/gather_scatter.f90
  src/simulation.f90
Labels: enhancement, GPU, NVIDIA

#664 Cleanup profiler intf and add support for ROCTX regions
  configure.ac
  m4/ax_roctx.m4
  src/.depends
  src/Makefile.am
  src/common/profiler.F90
  src/device/device.F90
  src/device/hip/roctx.F90
Labels: enhancement, GPU, AMD

#666 Add CrayPat support in profiler
  src/.depends
  src/Makefile.am
  src/common/craypat.F90
  src/common/profiler.F90
  src/fluid/fluid_pnpn.f90
Labels: enhancement, Cray

#667 Example fix
  examples/2d_cylinder/README.md
  examples/hemi/README.md
  examples/poisson/README.md
Labels: documentation

#661 Fix invalid offset in HIP async. GS pack
  src/gs/bcknd/device/hip/gs.hip
Labels: bug, GPU, AMD

#668 Improve quality and reduce time spent in gs auto-tune
  src/gs/gather_scatter.f90
Labels: enhancement

#669 Fix overflow in reported avg. internal gs for large problems
  src/gs/gather_scatter.f90
Labels: bug

#673 Patch pFUnit, fixing integration tests
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: bug

#674 Fix tests after change to symmetric notation
  src/mesh/hex.f90
  src/mesh/quad.f90
  tests/dofmap/dofmap_parallel.pf
  tests/gather_scatter/gather_scatter_parallel.pf
  tests/hex/hex.pf
  tests/mesh/mesh_parallel.pf
  tests/quad/quad.pf
Labels: bug

#675 Fix vtk output after change to sym.
  src/io/vtk_file.f90
Labels: bug

#676 Change probing method in hash table
  src/adt/htable.f90
Labels: enhancement

#677 Cleanup and reduce (host) memory usage in device GMRES
  src/krylov/bcknd/device/cuda/gmres_kernel.h
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/hip/gmres_kernel.h
Labels: GPU, NVIDIA, AMD

#678 Merge col2 kernels in device_curl
  src/.depends
  src/math/bcknd/device/opr_device.F90
Labels: GPU, NVIDIA, AMD

#679 Fix invalid HIP_HIPCC_FLAGS for roctx
  m4/ax_roctx.m4
Labels: bug, GPU, AMD

#680 Specify minim autoconf version, and fix obsolete macros in .ac and .m4 files
  configure.ac
  m4/ax_cuda.m4
  m4/ax_hip.m4
  m4/ax_libxsmm.m4
  m4/ax_nccl.m4
  m4/ax_nvtx.m4
  m4/ax_opencl.m4
  m4/ax_rccl.m4
  m4/ax_roctx.m4
Labels: enhancement

#681 Fixed various regression bugs due to refactored interfaces
  bench/tgv32/tgv.f90
  reframe/checks.py
  reframe/src/tgv.f90
Labels: bug

#683 Rea2nbin fixes
  src/adt/htable.f90
  src/io/re2_file.f90
  src/mesh/mesh.f90
Labels: enhancement

#684 Always use i8 based hashing
  src/adt/htable.f90
Labels: enhancement

#682 Feature/glsc3 xy swap tuning
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
Labels: GPU, NVIDIA, AMD

#687 Don't tune comm. strategy for single device runs
  src/gs/gather_scatter.f90
Labels: GPU, NVIDIA, AMD

#691 Cleanup in Scalar solver
  src/scalar/scalar_method.f90
  src/scalar/scalar_pnpn.f90
Labels: bug

#692 Fix fld file for NAG compiler
  src/io/fld_file.f90
Labels: bug, compilers

#693 Don't copy the same data several times
  src/io/scalar_output.f90
Labels: bug, GPU

#696 Cleanup and reduced memory footprint for scalars
  src/.depends
  src/case.f90
  src/scalar/scalar_method.f90
  src/scalar/scalar_pnpn.f90
Labels: enhancement

#697 Add NEKO_BCKND_DEVICE config flag
  bench/tgv32/tgv.f90
  configure.ac
  examples/turbpipe/pipe.f90
  reframe/src/tgv.f90
  src/bc/bc.f90
  src/common/checkpoint.f90
  src/common/ext_bdf_scheme.f90
  src/common/rhs_maker_fctry.f90
  src/common/source.f90
  src/common/source_scalar.f90
  src/config/neko_config.f90.in
  src/field/field.f90
  src/field/mean_field.f90
  src/field/mean_sqr_field.f90
  src/fluid/advection.f90
  src/fluid/flow_ic.f90
  src/fluid/fluid_fctry.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_volflow.f90
  src/fluid/pnpn_res_fctry.f90
  src/gs/gather_scatter.f90
  src/io/fluid_output.f90
  src/io/scalar_output.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/krylov/pc_hsmg.f90
  src/krylov/precon_fctry.f90
  src/math/ax_helm_fctry.f90
  src/math/fdm.f90
  src/math/operators.f90
  src/math/schwarz.f90
  src/scalar/scalar_pnpn.f90
  src/sem/coef.f90
  src/sem/dofmap.f90
  src/sem/interpolation.f90
  src/sem/space.f90
Labels: enhancement, GPU

#698 Fix postprocessing in TGV example for devices
  examples/tgv/tgv.f90
Labels: bug, GPU
