Repository ExtremeFLOW/neko, pull requests merged in 2022-09, with the labels that each got.

#595 Silence compiler warnings in ax_helm (HIP w. CCE)
  src/math/bcknd/device/hip/ax_helm.hip
Labels: bug, Cray, AMD

#596 fixed sizes in glsc3_many
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/opencl/math.c
Labels: bug, GPU

#594 Runtime selection of Sync. / Async. gs pack/unpack w. device MPI
  src/device/cuda_intf.F90
  src/device/device.F90
  src/device/hip_intf.F90
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/gs_device_mpi.F90
  src/gs/bcknd/device/hip/gs.hip
  src/gs/bcknd/device/hip/gs_kernels.h
  src/gs/gather_scatter.f90
Labels: enhancement, GPU, NVIDIA, AMD

#597 Fix ptr issue in gs rt for CCE
  src/gs/gather_scatter.f90
Labels: bug, GPU, Cray, AMD

#598 Reduce malloc/free calls during reductions (device)
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/opencl/math.c
Labels: enhancement, GPU

#599 Add methods to cleanup address table for deallocated device pointers
  src/device/device.F90
Labels: enhancement, GPU

#600 Cleanup device address table during gs rt
  src/gs/gather_scatter.f90
Labels: GPU

#602 Fix/pin memory in glsc3
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/opencl/math.c
Labels: GPU

#603 Python Neko -- pyNeko
  contrib/pyneko/Makefile.am
  contrib/pyneko/README.md
  contrib/pyneko/configure.ac
  contrib/pyneko/examples/hemi/hemi.nmsh
  contrib/pyneko/examples/hemi/hemi.py
  contrib/pyneko/pyNeko/__init__.py
  contrib/pyneko/pyNeko/case.py
  contrib/pyneko/pyNeko/intf.py
  contrib/pyneko/regen.sh
  contrib/pyneko/src/Makefile.am
  contrib/pyneko/src/json_case.f90
  contrib/pyneko/src/neko_intf.f90
  src/common/parameters.f90
Labels: enhancement

#604 Minor fixes in Doxygen file to document all defines
  doc/Doxyfile.in
Labels: documentation

#605 updated glsc3 routines to pin the malloc in all glsc3 routines
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/opencl/math.c
Labels: bug, GPU

#606 Fix (re)size of gmres reduction buffers
  src/krylov/bcknd/device/cuda/gmres_aux.cu
  src/krylov/bcknd/device/hip/gmres_aux.hip
Labels: bug, GPU, NVIDIA, AMD

#607 Change to pinned memory for red. buffers in gmres
  src/krylov/bcknd/device/cuda/gmres_aux.cu
  src/krylov/bcknd/device/hip/gmres_aux.hip
Labels: GPU, NVIDIA, AMD

#608 Fix invalid use of pinned memory in OpenCL, causing a runtime crash
  src/math/bcknd/device/opencl/math.c
Labels: bug, GPU

#609 Don't init. projection for a zero dimensional space
  src/fluid/fluid_pnpn.f90
Labels: bug, GPU

#610 Fix uninitialized variable in projection
  src/common/projection.f90
Labels: bug

#611 Don't pollute Neko's preprocessor flags with ADIOS2's CXX flags
  m4/ax_adios.m4
Labels: bug

#615 Feature/glsc3 optimisation
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
Labels: enhancement, GPU, NVIDIA, AMD

#613 Add hooks to link against NCCL
  configure.ac
  m4/ax_nccl.m4
Labels: enhancement, GPU, NVIDIA

#616 Add hooks to link against RCCL
  configure.ac
  m4/ax_rccl.m4
Labels: enhancement, GPU, AMD

#617 Don't try to compare spaces for non existant fields
  src/field/field.f90
Labels: bug

#614 Feature/field registry
  src/.depends
  src/Makefile.am
  src/field/field_registry.f90
  src/fluid/fluid_method.f90
  src/neko.f90
Labels: enhancement

#618 Retire plan4 solver, change all examples to pnpn
  bench/tgv32/tgv.case
  examples/compression/tgv.case
  examples/hemi/hemi.case
  examples/tgv/tgv.case
  examples/turbChannel/turbChannel.case
  src/fluid/fluid_plan4.f90
Labels: enhancement

#619 Add checks such that fluid fields are registered before starting a solve
  src/fluid/fluid_method.f90
Labels: enhancement

#620 Speedup offline tools, only generating connectivity when needed
  contrib/prepart/prepart.f90
  contrib/rea2nbin/rea2nbin.f90
  src/mesh/mesh.f90
Labels: enhancement

#621 Hide common names in order to make Doxygen less confused
  src/field/field_registry.f90
Labels: documentation

#623 Feature/pi
  src/math/math.f90
Labels: enhancement

#624 fixed some inconsistencies in doxygen for mathops
  src/math/mathops.f90
Labels: documentation

#631 updates to tgv example
  examples/tgv/tgv.case
  examples/tgv/tgv.f90
Labels: documentation

#635 added new example case: 3D lid-driven cavity
  examples/lid/lid.box
  examples/lid/lid.case
  examples/lid/lid.f90
  examples/lid/lid.nmsh
Labels: enhancement, new case

#637 Reduce memory traffic in abbdf CUDA kernels
  src/fluid/bcknd/device/cuda/fluid_abbdf.cu
  src/fluid/bcknd/device/cuda/makeabf_kernel.h
  src/fluid/bcknd/device/cuda/makebdf_kernel.h
  src/fluid/bcknd/device/fluid_abbdf_device.F90
Labels: enhancement, NVIDIA

#638 added 2d lid driven cavity
  examples/lid/lid2d.box
  examples/lid/lid2d.case
  examples/lid/lid2d.f90
  examples/lid/lid2d.nmsh
Labels: new case

#639 Use a blasius profile in the hemi example
  examples/hemi/hemi.case
Labels: bug

#643 Transpose glsc3_many kernel, improving memory traffic
  src/math/bcknd/device/cuda/math_kernel.h
Labels: GPU, NVIDIA

#644 added correct sampling at initial time
  src/simulation.f90
Labels: enhancement
