Repository ExtremeFLOW/neko, pull requests merged in 2022-06, with the labels that each got.

#542 Explicitly figure out the class family
  src/io/file.f90
Labels: bug, compilers, Cray

#546 Support for reading STL files
  src/.depends
  src/Makefile.am
  src/comm/mpi_types.f90
  src/io/file.f90
  src/io/format/stl.f90
  src/io/stl_file.f90
  src/mesh/tet_mesh.f90
  src/mesh/tri_mesh.f90
Labels: enhancement

#548 Fix invalid unit test for 2i4r8t3 stacks
  tests/stack/stack_2i4r8t3.pf
Labels: bug

#550 Padded version of ax_helm_kernel on CUDA to fix Bank Conflicts
  src/math/bcknd/device/cuda/ax_helm.cu
  src/math/bcknd/device/cuda/ax_helm_kernel.h
Labels: GPU, NVIDIA

#551 Fix format specifier
  src/common/sampler.f90
Labels: bug

#552 Bugfix pipecg
  src/krylov/bcknd/device/pipecg_device.F90
Labels: bug, GPU

#555 Add volflow for fluid_pnpn
  src/.depends
  src/Makefile.am
  src/fluid/fluid_abbdf_fctry.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_volflow.f90
Labels: enhancement

#556 Add support for device backend in volflow
  src/.depends
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_volflow.f90
Labels: bug, enhancement, GPU

#558 NEKO v0.4.2
  configure.ac
  src/krylov/bcknd/device/pipecg_device.F90
Labels: bug, GPU
