Repository ExtremeFLOW/neko, pull requests merged in 2022-08, with the labels that each got.

#571 NEKO v0.4.3
  .github/workflows/develop.yml
  .github/workflows/main.yml
  configure.ac
  m4/ax_cray.m4
  src/comm/redist.f90
  src/common/sampler.f90
  src/device/hip_intf.F90
Labels: bug

#572 Fix homebrew issues with macOS gh-actions
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: bug

#573 Honor user specified HIPCC for Cray's ROCm Toolkit on EX platforms
  m4/ax_cray.m4
Labels: compilers, GPU, Cray, AMD

#574 Cleanup bicgstab with an assoc. block and proper usage of working precision
  src/krylov/bcknd/cpu/bicgstab.f90
Labels: enhancement

#575 Avoid linking against Fortran libraries when testing for nvcc/hipcc
  m4/ax_cuda.m4
  m4/ax_hip.m4
Labels: bug, GPU, NVIDIA, AMD

#576 Add support for storing points in a stack
  src/.depends
  src/adt/stack.f90
  tests/Makefile.am
  tests/stack/Makefile.in
  tests/stack/stack_pt.pf
Labels: enhancement

#577 Add an octree for fast point searches
  configure.ac
  src/.depends
  src/Makefile.am
  src/mesh/octree.f90
  tests/Makefile.am
  tests/octree/Makefile.in
  tests/octree/octree.pf
Labels: enhancement

#579 Feature/ax kernel optimisation on amd gpu
  src/math/bcknd/device/hip/ax_helm.hip
  src/math/bcknd/device/hip/ax_helm_kernel.h
Labels: enhancement, GPU, AMD

#581 Route axhelm autotune output to neko's log backend
  src/math/bcknd/device/hip/ax_helm.hip
Labels: enhancement

#582 Fix invalid accelerator example
  doc/pages/accelerators.md
Labels: documentation

#578 Dreamhack - Interpolation between checkpoint with different polynomial degrees
  src/common/sampler.f90
  src/io/chkp_file.f90
  src/io/file.f90
  src/io/fld_file.f90
  src/io/generic_file.f90
  src/io/output.f90
  src/sem/interpolation.f90
  src/simulation.f90
Labels: enhancement

#584 Output more params. to log during init.
  src/common/sampler.f90
  src/fluid/fluid_method.f90
  src/fluid/fluid_plan1.f90
  src/fluid/fluid_plan4.f90
  src/fluid/fluid_pnpn.f90
Labels: enhancement

#586 Feature/low order mg
  src/krylov/pc_hsmg.f90
Labels: enhancement

#587 Ensure that Doxygen documents all possible preprocessor options
  doc/Doxyfile.in
Labels: documentation

#588 Adjust htable growth factor
  src/adt/htable.f90
Labels: enhancement

#589 Add pkg.m4 to avoid issues on certain pokemon linux distributions...
  m4/pkg.m4
Labels: bug, compilers

#590 Fix buffer issue when pipecg is used for both vel. and prs.
  src/krylov/bcknd/device/cuda/pipecg_aux.cu
  src/krylov/bcknd/device/hip/pipecg_aux.hip
Labels: bug, GPU, NVIDIA, AMD

#591 Add support for CUDA/HIP Streams
  src/device/cuda_intf.F90
  src/device/device.F90
  src/device/hip_intf.F90
Labels: enhancement, GPU, NVIDIA, AMD
