Repository ExtremeFLOW/neko, pull requests merged in 2023-05, with the labels that each got.

#840 Add a docstring for conv1
  src/math/operators.f90
Labels: documentation

#821 Dealiased scalar
  src/fluid/advection.f90
  src/scalar/scalar_pnpn.f90
  tests/Makefile.am
Labels: enhancement

#844 Output CPU type
  configure.ac
  src/.depends
  src/Makefile.am
  src/common/cpuid.c
  src/common/system.f90
  src/neko.f90
Labels: enhancement

#847 Disable nvhpc builds for develop CI
  .github/workflows/develop.yml
Labels: compilers, NVIDIA, CI

#849 Disable nvhpc in release CI
  .github/workflows/main.yml
Labels: compilers, NVIDIA, CI

#850 Fixed regression in OpenCL gs
  src/gs/bcknd/device/gs_device.F90
Labels: bug, GPU, OpenCL

#860 Only output to log if a data is written
  src/common/sampler.f90
  src/simulation.f90
Labels: enhancement

#861 Check if CrayPE wrappers are used on Cray EX systems
  configure.ac
  m4/ax_cray.m4
Labels: bug, compilers, Cray

#862 Add missing stats params to documentation
  doc/pages/case-file.md
Labels: documentation

#865 Scalar user bc
  examples/rayleigh-benard/rayleigh.case
  examples/rayleigh-benard/rayleigh.f90
  src/bc/bcknd/device/cuda/inhom_dirichlet.cu
  src/bc/bcknd/device/cuda/inhom_dirichlet_kernel.h
  src/bc/bcknd/device/device_inhom_dirichlet.F90
  src/bc/bcknd/device/hip/inhom_dirichlet.hip
  src/bc/bcknd/device/hip/inhom_dirichlet_kernel.h
  src/bc/bcknd/device/opencl/inhom_dirichlet.c
  src/bc/bcknd/device/opencl/inhom_dirichlet_kernel.cl
  src/bc/usr_inflow.f90
  src/case.f90
  src/common/user_intf.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#870 Fix SIGFPE (for intel and cce) in sampler output logic
  src/common/sampler.f90
Labels: bug, compilers, Cray

#877 Fix user code in the lid2d example
  examples/lid/lid2d.f90
Labels: bug
