Repository ExtremeFLOW/neko, pull requests merged in 2023-02, with the labels that each got.

#771 Fix issues with runners and nvfortran + cuda
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: bug, NVIDIA, CI

#770 Device vdot3
  src/fluid/advection.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
Labels: enhancement, GPU, NVIDIA, AMD, OpenCL

#769 Remove leaf routines, improving loop fusion
  src/sem/coef.f90
Labels: enhancement

#772 Add profiler regions to cover most steps of a simulation
  src/.depends
  src/common/projection.f90
  src/fluid/fluid_pnpn.f90
  src/krylov/pc_hsmg.f90
  src/scalar/scalar_pnpn.f90
Labels: enhancement

#773 Fix out ouf bounds in divergence checks
  src/scalar/scalar_aux.f90
Labels: bug

#778 optimised schwarz extrude for CUDA
  src/math/bcknd/device/cuda/schwarz.cu
  src/math/bcknd/device/cuda/schwarz_kernel.h
Labels: GPU, NVIDIA

#779 Fix projections for OpenCL backend
  src/common/projection.f90
Labels: enhancement, GPU, OpenCL

#781 Add small nelv guards in re2 file reader
  src/io/re2_file.f90
Labels: bug

#782 Add support for OpenCL in GMRES solver
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/krylov_fctry.f90
Labels: GPU, OpenCL

#783 Fix array thing for curved elements
  src/mesh/curve.f90
Labels: bug, compilers, Cray

#784 Improve Ax helm perf on MI250X
  src/math/bcknd/device/hip/ax_helm_kernel.h
Labels: GPU, AMD

#787 Add kstep version of CUDA/HIP kernels
  src/math/bcknd/device/cuda/cdtp_kernel.h
  src/math/bcknd/device/cuda/conv1_kernel.h
  src/math/bcknd/device/cuda/dudxyz_kernel.h
  src/math/bcknd/device/cuda/opgrad_kernel.h
  src/math/bcknd/device/cuda/opr_cdtp.cu
  src/math/bcknd/device/cuda/opr_conv1.cu
  src/math/bcknd/device/cuda/opr_dudxyz.cu
  src/math/bcknd/device/cuda/opr_opgrad.cu
  src/math/bcknd/device/hip/cdtp_kernel.h
  src/math/bcknd/device/hip/conv1_kernel.h
  src/math/bcknd/device/hip/dudxyz_kernel.h
  src/math/bcknd/device/hip/opgrad_kernel.h
  src/math/bcknd/device/hip/opr_cdtp.hip
  src/math/bcknd/device/hip/opr_conv1.hip
  src/math/bcknd/device/hip/opr_dudxyz.hip
  src/math/bcknd/device/hip/opr_opgrad.hip
Labels: enhancement, GPU, NVIDIA, AMD

#788 Fix compiler errors when using CCE (v14.0.2) as HIP compiler
  src/math/bcknd/device/hip/cdtp_kernel.h
Labels: bug, compilers, GPU, Cray, AMD
