Repository ExtremeFLOW/neko, pull requests merged in 2023-04, with the labels that each got.

#814 Refactor ext_bdf_scheme_t
  src/case.f90
  src/common/ext_bdf_scheme.f90
  src/fluid/bcknd/device/device_fluid_plan4.f90
  src/fluid/fluid_plan4.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_volflow.f90
  src/scalar/scalar_pnpn.f90
  src/simulation.f90
Labels: Refactor

#812 Add output fields from examples to .gitignore
  .gitignore
Labels: enhancement

#811 Improvements and tests for fd_weights_full
  configure.ac
  src/math/fast3d.f90
  tests/.gitignore
  tests/Makefile.am
  tests/fast3d/Makefile.in
  tests/fast3d/test_fd_weights_full.pf
Labels: documentation

#813 Scratch registry improvements
  src/field/scratch_registry.f90
  tests/scratch_registry/test_scratch_registry.pf
Labels: enhancement

#818 Hotfix time_scheme%n initialization
  src/common/ext_bdf_scheme.f90
Labels: bug

#826 Fix invalid CFLAGS for NVCC
  m4/ax_cuda.m4
  m4/ax_nvtx.m4
Labels: bug, GPU, NVIDIA

#820 Cleanup of bdf_time_scheme_t; adding its docs and tests
  .github/workflows/develop.yml
  configure.ac
  src/common/bcknd/cpu/rhs_maker_cpu.f90
  src/common/bcknd/device/rhs_maker_device.F90
  src/common/bcknd/sx/rhs_maker_sx.f90
  src/common/ext_bdf_scheme.f90
  src/common/rhs_maker.f90
  src/fluid/bcknd/device/fluid_abbdf_device.F90
  tests/.gitignore
  tests/Makefile.am
  tests/ext_bdf_scheme/Makefile.in
  tests/ext_bdf_scheme/test_bdf.pf
Labels: documentation, enhancement

#832 Fix array size in call to rzero in the EXT time scheme
  src/common/ext_bdf_scheme.f90
Labels: bug

#799 Max iter
  examples/lid/lid.case
  examples/lid/lid2d.case
  src/comm/mpi_types.f90
  src/common/parameters.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_volflow.f90
  src/scalar/scalar_pnpn.f90
Labels: enhancement

#834 Fix invalid size in device memcpy
  src/common/ext_bdf_scheme.f90
Labels: bug, GPU, NVIDIA, AMD

#835 Change to pinned memory and warp reductions in pipecg
  src/krylov/bcknd/device/cuda/pipecg_aux.cu
  src/krylov/bcknd/device/cuda/pipecg_kernel.h
  src/krylov/bcknd/device/hip/pipecg_aux.hip
  src/krylov/bcknd/device/hip/pipecg_kernel.h
Labels: GPU, NVIDIA, AMD

#836 Fix build with CCE v15.0.1
  src/comm/redist.f90
  src/mesh/curve.f90
Labels: bug, compilers, Cray

#819 Harmonize file, module and class name for fluid_scheme and scalar_scheme
  src/.depends
  src/Makefile.am
  src/fluid/fluid_fctry.f90
  src/fluid/fluid_plan1.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/io/fld_file.f90
  src/io/fluid_output.f90
  src/io/scalar_output.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
Labels: refactor
