Repository ExtremeFLOW/neko, pull requests merged in 2023-11, with the labels that each got.

#1016 Add instructions to run Neko using the Docker container
  doc/pages/installation.md
Labels: documentation

#1026 Add ParMETIS instructions
  doc/pages/installation.md
Labels: documentation

#1009 Add governing equations page, update case-file for sources and material props.
  doc/Doxyfile.in
  doc/pages/case-file.md
  doc/pages/governing-equations.md
  doc/pages/index.md
Labels: documentation

#1011 Fix privacy and imports in krylov solvers
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/bcknd/sx/pnpn_res_sx.f90
  src/fluid/fluid_volflow.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/krylov/precon.f90
  src/math/ax.f90
  src/math/ax_helm_fctry.f90
  src/math/bcknd/cpu/ax_helm.f90
  src/math/bcknd/device/ax_helm_device.F90
  src/math/bcknd/sx/ax_helm_sx.f90
  src/math/bcknd/xsmm/ax_helm_xsmm.F90
Labels: documentation, refactor

#1028 Move finalize and map in point zone factory
  src/.depends
  src/mesh/point_zone.f90
  src/mesh/point_zone_factory.f90
  src/mesh/point_zones/box_point_zone.f90
  src/mesh/point_zones/sphere_point_zone.f90
Labels: refactor

#1029 Add instructions for building from source
  doc/pages/installation.md
Labels: documentation

#1031 Add OpenCL kernel for tensor el list
  src/math/bcknd/device/opencl/tensor.c
  src/math/bcknd/device/opencl/tensor_kernel.cl
  src/math/bcknd/device/tensor_device.F90
Labels: enhancement, GPU, OpenCL

#1038 Fix CI for Intel compilers
  .github/workflows/develop.yml
Labels: CI

#1039 Scalar Initial Condition
  doc/pages/case-file.md
  examples/rayleigh-benard-cylinder/rayleigh.case
  examples/rayleigh-benard-cylinder/rayleigh.f90
  examples/rayleigh-benard/rayleigh.case
  examples/rayleigh-benard/rayleigh.f90
  reframe/src/rayleigh.case.template
  reframe/src/rayleigh.f90
  src/.depends
  src/Makefile.am
  src/case.f90
  src/common/user_intf.f90
  src/scalar/scalar_ic.f90
Labels: enhancement

#1042 Avoid potential name clash with mpi_types module
  src/.depends
  src/case.f90
  src/comm/mpi_types.f90
  src/comm/redist.f90
  src/common/global_interpolation.F90
  src/io/chkp_file.f90
  src/io/data_streamer.F90
  src/io/fld_file.f90
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/io/stl_file.f90
  src/neko.f90
  src/simulation_components/probes.F90
Labels: bug, compilers, CI

#1043 Fix invalid access in centroid calculation
  src/mesh/tri.f90
Labels: bug

#1045 Fix invalid precision in speclib
  src/sem/speclib.f90
Labels: bug, compilers
