Repository ExtremeFLOW/neko, pull requests merged in 2023-03, with the labels that each got.

#789 Don't pass all C++ related LDFLAGS to nvcc
  m4/ax_cuda.m4
Labels: bug, compilers, NVIDIA

#790 Time-dependent source terms
  examples/rayleigh-benard/rayleigh.f90
  examples/turbpipe/pipe.f90
  reframe/src/rayleigh.f90
  src/common/source.f90
  src/common/user_intf.f90
  src/fluid/bcknd/device/device_fluid_plan4.f90
  src/fluid/fluid_plan4.f90
  src/fluid/fluid_pnpn.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/source_scalar.f90
Labels: enhancement

#791 Generate geometric factors up to LX 16
  src/sem/bcknd/device/cuda/coef.cu
  src/sem/bcknd/device/hip/coef.hip
Labels: enhancement, GPU, NVIDIA, AMD

#792 Generate geometric factors up to LX 16 (OpenCL)
  src/sem/bcknd/device/opencl/coef.c
  src/sem/bcknd/device/opencl/coef_kernel.cl
Labels: GPU, OpenCL

#793 Remove unused fields and components from Scalar solver
  src/scalar/scalar_pnpn.f90
Labels: enhancement

#797 Update channel flow example
  examples/turbChannel/README.md
  examples/turbChannel/box.nmsh
  examples/turbChannel/channel.f90
  examples/turbChannel/turbChannel.case
  examples/turbChannel/turbChannel.nmsh
Labels: new case

#798 Add strain rate operator
  src/math/operators.f90
Labels: enhancement

#802 Add device events
  src/device/cuda_intf.F90
  src/device/device.F90
  src/device/hip_intf.F90
Labels: enhancement, GPU, NVIDIA, AMD

#803 Async. gather-scatter
  src/device/cuda_intf.F90
  src/device/device.F90
  src/device/hip_intf.F90
  src/gs/bcknd/device/gs_device.F90
  src/gs/bcknd/device/gs_device_mpi.F90
  src/gs/gather_scatter.f90
  src/gs/gs_bcknd.f90
  src/gs/gs_comm.f90
  src/gs/gs_mpi.f90
Labels: enhancement, GPU, NVIDIA, AMD

#807 Scratch registry, test documentation better gitignores
  .gitignore
  configure.ac
  doc/Doxyfile.in
  doc/pages/testing.md
  src/.depends
  src/Makefile.am
  src/field/scratch_registry.f90
  tests/.gitignore
  tests/Makefile.am
  tests/scratch_registry/Makefile.in
  tests/scratch_registry/test_scratch_registry.pf
Labels: documentation, enhancement

#808 Fix race condition in gather-scatter (strtgy > 2)
  src/gs/bcknd/device/gs_device_mpi.F90
Labels: bug, GPU, NVIDIA, AMD
