Repository ExtremeFLOW/neko, pull requests merged in 2023-12, with the labels that each got.

#1046 Cleanup invalid/unused use statements
  src/.depends
  src/adt/stack.f90
  src/bc/bc.f90
  src/case.f90
  src/common/json_utils.f90
  src/common/material_properties.f90
  src/field/scratch_registry.f90
  src/fluid/flow_ic.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_user_source_term.f90
  src/fluid/fluid_volflow.f90
  src/fluid/pnpn_res.f90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/math/ax.f90
  src/math/bcknd/cpu/ax_helm.f90
  src/math/bcknd/cpu/opr_cpu.f90
  src/math/bcknd/device/ax_helm_device.F90
  src/math/bcknd/sx/ax_helm_sx.f90
  src/math/bcknd/sx/opr_sx.f90
  src/math/bcknd/xsmm/ax_helm_xsmm.F90
  src/math/schwarz.f90
  src/mesh/curve.f90
  src/scalar/scalar_pnpn.f90
  src/sem/dofmap.f90
  src/sem/interpolation.f90
  src/sem/point_interpolator.f90
  src/sem/spectral_error_indicator.f90
  src/simulation.f90
  src/simulation_components/lambda2.f90
  src/simulation_components/probes.F90
  src/time_schemes/time_scheme.f90
Labels: enhancement

#1048 Backport restart fixes to 0.7 release branch
  src/case.f90
  src/common/checkpoint.f90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/io/chkp_file.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
  src/simulation.f90
Labels: bug

#1050 Fix invalid error if gslib is not found
  src/common/global_interpolation.F90
Labels: bug

#1054 Replace deprecated OpenCL call (clEnqueueMarker)
  src/device/device.F90
  src/device/opencl_intf.F90
Labels: OpenCL

#1047 Restart simulation fixes
  src/case.f90
  src/common/checkpoint.f90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/io/chkp_file.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
  src/simulation.f90
Labels: bug

#1062 OpenCL: A trivial fix for error checking
  src/device/device.F90
Labels: OpenCL

#1060 Fix invalid error messages and ifdefs in device layer for OpenCL
  src/device/device.F90
Labels: bug, GPU, OpenCL

#1064 Extend nvtx markers to support (optional) colours
  src/common/profiler.F90
  src/common/projection.f90
  src/device/cuda/nvtx.F90
  src/fluid/fluid_pnpn.f90
  src/gs/gather_scatter.f90
  src/krylov/pc_hsmg.f90
  src/scalar/scalar_pnpn.f90
Labels: enhancement, GPU, NVIDIA

#1068 CI fixes for horrible homebrew
  .github/workflows/develop.yml
Labels: CI

#1071 Makes the strain rate operator public
  src/math/operators.f90
Labels: bug

#1073 Fix uninitialised flow_rate for non bulk flow
  .github/workflows/develop.yml
  .github/workflows/main.yml
  src/fluid/fluid_volflow.f90
Labels: bug

#1078 Add 'm' curvature type to rea_file
  src/io/rea_file.f90
Labels: bug

#1080 Manually set vec and mat to null in `csv_file_write`
  src/io/csv_file.f90
Labels: bug

#1074 Use the global scratch manager for scalar rhs
  src/common/bcknd/cpu/rhs_maker_cpu.f90
  src/common/bcknd/device/rhs_maker_device.F90
  src/common/bcknd/sx/rhs_maker_sx.f90
  src/common/rhs_maker.f90
  src/scalar/bcknd/cpu/scalar_residual_cpu.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_residual.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1075 Add possibility to prescribe execution order to simcomps
  src/.depends
  src/Makefile.am
  src/neko.f90
  src/simulation.f90
  src/simulation_components/simcomp_executor.f90
  src/simulation_components/simulation_component.f90
  src/simulation_components/simulation_component_global.f90
Labels: enhancement
