Repository ExtremeFLOW/neko, pull requests merged in 2023-09, with the labels that each got.

#948 Fix invalid path in m4 macro
  m4/ax_gslib.m4
Labels: bug

#949 Add controllers to simcomps
  examples/tgv/tgv.case
  src/simulation_components/simulation_component.f90
  src/simulation_components/vorticity.f90
Labels: enhancement

#950 Adds output control "never" and throw for non-positive nsamples
  doc/pages/case-file.md
  reframe/src/rayleigh.case.template
  src/case.f90
  src/common/time_based_controller.f90
Labels: enhancement

#963 Add opencl kernel for lambda2
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/math/bcknd/device/opencl/lambda2_kernel.cl
  src/math/bcknd/device/opencl/opr_lambda2.c
  src/math/bcknd/device/opr_device.F90
Labels: enhancement, GPU, OpenCL

#964 Fix lambda2 device deps. and add missing xsmm and sx backends.
  src/.depends_device
  src/math/operators.f90
Labels: SX, GPU

#971 Update accelerator page for new (default) async memcpy
  doc/pages/accelerators.md
Labels: bug, documentation

#976 Ensure memcopies sync on the correct stream
  src/device/device.F90
  tests/device/device.pf
  tests/device_math/device_math_parallel.pf
Labels: bug, GPU, NVIDIA, AMD

#973 Make mesh private, with type-bound procedures
  contrib/genmeshbox/genmeshbox.f90
  contrib/prepart/prepart.f90
  contrib/rea2nbin/rea2nbin.f90
  examples/poisson/ax_poisson.f90
  examples/poisson/driver.f90
  examples/poisson/setup.f90
  src/.depends
  src/case.f90
  src/comm/redist.f90
  src/io/fld_file.f90
  src/io/format/rea.f90
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/io/rea_file.f90
  src/io/vtk_file.f90
  src/krylov/pc_hsmg.f90
  src/mesh/mesh.f90
  src/neko.f90
  src/scalar/scalar_scheme.f90
  src/sem/dofmap.f90
  tests/dofmap/dofmap_parallel.pf
  tests/field/field_parallel.pf
  tests/gather_scatter/gather_scatter_parallel.pf
  tests/mean_field/mean_field_parallel.pf
  tests/mean_sqr_field/mean_sqr_field_parallel.pf
  tests/mesh/mesh_parallel.pf
  tests/point_interpolation/point_interpolation_parallel.pf
  tests/scratch_registry/test_scratch_registry.pf
Labels: enhancement

#975 Make coef private, with type-bound procedures
  contrib/average_field_in_space/average_field_in_space.f90
  contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90
  src/bc/dong_outflow.f90
  src/fluid/advection.f90
  src/fluid/fluid_plan1.f90
  src/fluid/fluid_scheme.f90
  src/krylov/pc_hsmg.f90
  src/sem/coef.f90
  tests/point_interpolation/point_interpolation_parallel.pf
Labels: enhancement

#974 Make field private, with type-bound procedures
  contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90
  examples/tgv/tgv.f90
  reframe/src/tgv.case.template
  reframe/src/tgv.f90
  src/.depends
  src/bc/dong_outflow.f90
  src/common/checkpoint.f90
  src/common/user_intf.f90
  src/field/field.f90
  src/field/field_registry.f90
  src/field/field_series.f90
  src/field/mean_field.f90
  src/field/scratch_registry.f90
  src/fluid/advection.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_stats.f90
  src/fluid/fluid_volflow.f90
  src/io/chkp_file.f90
  src/io/fld_file.f90
  src/krylov/pc_hsmg.f90
  src/math/schwarz.f90
  src/scalar/scalar_pnpn.f90
  src/sem/coef.f90
  src/simulation.f90
  src/simulation_components/lambda2.f90
  src/simulation_components/vorticity.f90
  tests/field/field_parallel.pf
  tests/gather_scatter/gather_scatter_parallel.pf
  tests/mean_field/mean_field_parallel.pf
  tests/mean_sqr_field/mean_sqr_field_parallel.pf
  tests/scratch_registry/test_scratch_registry.pf
Labels: enhancement

#978 Fix point_interpolator compiler warnings on Cray
  src/sem/point_interpolator.f90
Labels: compilers, Cray

#956 Feature/spectral error indicator
  src/.depends
  src/Makefile.am
  src/neko.f90
  src/sem/coef.f90
  src/sem/space.f90
  src/sem/spectral_error_indicator.f90
Labels: enhancement

#979 Feature/data stream adios2
  m4/ax_adios.m4
  src/.depends
  src/Makefile.am
  src/comm/comm.F90.in
  src/io/adios2_config/config.xml
  src/io/data_streamer.F90
  src/io/nek_adios2.cpp
  src/neko.f90
Labels: enhancement

#962 Run-time selectable sources
  doc/pages/case-file.md
  examples/cyl_boundary_layer/cyl_bl_user.case
  examples/rayleigh-benard-cylinder-probes/rayleigh.case
  examples/rayleigh-benard-cylinder-probes/rayleigh.f90
  examples/rayleigh-benard-cylinder/rayleigh.case
  examples/rayleigh-benard-cylinder/rayleigh.f90
  examples/rayleigh-benard/rayleigh.case
  examples/rayleigh-benard/rayleigh.f90
  examples/turbpipe/README.md
  examples/turbpipe/pipe.case
  examples/turbpipe/pipe.f90
  examples/turbpipe/pipe_source.case
  reframe/src/rayleigh.case.template
  reframe/src/rayleigh.f90
  reframe/src/tgv.case.template
  src/.depends
  src/Makefile.am
  src/case.f90
  src/common/source.f90
  src/common/user_intf.f90
  src/field/field_list.f90
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/bcknd/sx/pnpn_res_sx.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_source_term.f90
  src/fluid/fluid_user_source_term.f90
  src/fluid/pnpn_res.f90
  src/neko.f90
  src/scalar/scalar_scheme.f90
  src/source_terms/bcknd/cpu/const_source_term_cpu.f90
  src/source_terms/bcknd/device/const_source_term_device.f90
  src/source_terms/const_source_term.f90
  src/source_terms/source_term.f90
  src/source_terms/source_term_factory.f90
Labels: enhancement
