Repository ExtremeFLOW/neko, pull requests merged in 2023-06, with the labels that each got.

#880 Fix finalisation in bc
  src/bc/bc.f90
  src/bc/blasius.f90
  src/bc/non_normal.f90
  src/bc/symmetry.f90
  src/bc/usr_inflow.f90
Labels: bug, compilers, GPU

#879 Feature/user finalize
  examples/lid/lid.f90
  examples/lid/lid2d.f90
  examples/tgv/tgv.f90
  src/common/user_intf.f90
  src/simulation.f90
Labels: enhancement

#881 Add missing OpenCL features for "stream/events"
  src/device/device.F90
  src/device/opencl_intf.F90
Labels: enhancement, GPU, OpenCL

#882 Use correct OpenCL functions for event record and wait
  src/device/device.F90
  src/device/opencl_intf.F90
Labels: bug, GPU, OpenCL

#883 Structure manual
  doc/pages/index.md
Labels: documentation

#884 Improve docs for bc_t
  src/bc/bc.f90
Labels: documentation

#887 Make fdm private
  src/math/fdm.f90
  src/math/schwarz.f90
Labels: enhancement, compilers

#889 Re-enable nvhpc in CI
  .github/workflows/develop.yml
Labels: CI

#890 Fix sync. rules for non device aware MPI builds
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/hip/math.hip
Labels: bug, GPU, NVIDIA, AMD

#892 Edit documentation in fast3d
  src/math/fast3d.f90
Labels: documentation

#893 Fix memory leak in device pipelined CG
  src/krylov/bcknd/device/pipecg_device.F90
Labels: bug, GPU, NVIDIA, AMD, OpenCL

#894 Fix missing code path for OpenCL
  src/bc/dong_outflow.f90
Labels: bug, GPU, OpenCL

#809 Better temporaries handling in fluid
  src/case.f90
  src/common/bcknd/cpu/rhs_maker_cpu.f90
  src/common/bcknd/device/rhs_maker_device.F90
  src/common/bcknd/sx/rhs_maker_sx.f90
  src/common/rhs_maker.f90
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/bcknd/sx/pnpn_res_sx.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_volflow.f90
  src/fluid/pnpn_res.f90
  src/neko.f90
Labels: enhancement

#896 Add a proper user scalar bc module
  src/.depends
  src/Makefile.am
  src/bc/usr_inflow.f90
  src/bc/usr_scalar.f90
  src/common/user_intf.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#898 Add csv files input/output
  examples/lid/lid.f90
  examples/lid/lid2d.f90
  src/.depends
  src/Makefile.am
  src/comm/mpi_types.f90
  src/io/csv_file.f90
  src/io/file.f90
  src/io/generic_file.f90
  src/math/matrix.f90
  src/math/vector.f90
  src/mesh/mesh.f90
  src/mesh/point.f90
Labels: enhancement

#900 Interpolation of scalar/vector fields
  configure.ac
  src/.depends
  src/Makefile.am
  src/math/tensor.f90
  src/mesh/point.f90
  src/sem/interpolation.f90
  src/sem/point_interpolator.f90
  tests/.gitignore
  tests/Makefile.am
  tests/point_interpolation/Makefile.in
  tests/point_interpolation/point_interpolation_parallel.pf
  tests/point_interpolation/point_interpolation_test
Labels: enhancement
