Repository ExtremeFLOW/neko, pull requests merged in 2023-08, with the labels that each got.

#923 Update pc.in file to cover both lib and lib64 cases
  neko.pc.in
Labels: bug

#925 Ensure output_directory exist (or is created)
  src/case.f90
Labels: bug

#927 Remove unused output definitions
  src/.depends
  src/Makefile.am
  src/case.f90
  src/io/field_list_output.f90
Labels: enhancement

#926 Unify fluid and scalar output
  doc/pages/case-file.md
  src/.depends
  src/Makefile.am
  src/case.f90
  src/io/fld_file.f90
  src/io/fluid_output.f90
  src/io/scalar_output.f90
Labels: enhancement

#928 Add methods to pass down simulation time and/or time-step to bcs
  examples/cyl_boundary_layer/cyl_bl.f90
  examples/lid/lid.f90
  examples/lid/lid2d.f90
  examples/rayleigh-benard-cylinder/rayleigh.f90
  examples/rayleigh-benard/rayleigh.f90
  reframe/src/rayleigh.f90
  src/bc/bc.f90
  src/bc/blasius.f90
  src/bc/dirichlet.f90
  src/bc/dong_outflow.f90
  src/bc/facet_normal.f90
  src/bc/inflow.f90
  src/bc/symmetry.f90
  src/bc/usr_inflow.f90
  src/bc/usr_scalar.f90
  src/bc/wall.f90
  src/common/user_intf.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
Labels: enhancement, refactor

#929 Fix invalid check for optional args
  src/bc/bc.f90
Labels: bug

#930 Update case-file.md
  doc/pages/case-file.md
Labels: documentation

#931 Fixed regression bug in bc scalar apply
  src/bc/bc.f90
Labels: bug

#922 Put check on whether to execute an action based on time value in a separate class
  configure.ac
  src/.depends
  src/Makefile.am
  src/common/sampler.f90
  src/common/time_based_controller.f90
  tests/.gitignore
  tests/Makefile.am
  tests/time_based_controller/Makefile.in
  tests/time_based_controller/test_time_based_controller.pf
Labels: enhancement

#932 Add autotuning for CUDA Axhelm
  src/math/bcknd/device/ax_helm_device.F90
  src/math/bcknd/device/cuda/ax_helm.cu
  src/math/bcknd/device/cuda/ax_helm_kernel.h
Labels: enhancement, GPU, NVIDIA

#933 Fix ICE with frtpx 4.9.0
  src/fluid/fluid_scheme.f90
Labels: compilers, Fujitsu

#934 Fix cpu detection on PowerPC and A64FX
  src/common/cpuid.c
Labels: compilers, Fujitsu

#935 Reduce required thread support level for CPU only builds
  src/.depends
  src/comm/comm.F90.in
Labels: compilers, OpenMP

#937 Rework MPI init, try to use MULTIPLE (if present) even for cpu backends
  src/comm/comm.F90.in
Labels: enhancement, OpenMP

#940 Change type
  bench/tgv32/tgv.f90
Labels: bug

#942 Bugfix/optional in user file
  examples/cyl_boundary_layer/cyl_bl.f90
  examples/lid/lid.f90
  examples/lid/lid2d.f90
Labels: bug

#944 Update doxygen workflow with new deps. (JSON Fortran)
  .github/workflows/documentation.yml
Labels: bug, documentation

#946 Ensure each thread is assigned to the same device
  src/device/cuda_intf.F90
Labels: bug, GPU, NVIDIA, OpenMP
