Repository ExtremeFLOW/neko, pull requests merged in 2023-01, with the labels that each got.

#755 added NVTX flags to sampler
  src/common/sampler.f90
Labels: GPU, NVIDIA

#756 Fix missing target in ptr assignment
  src/adt/htable.f90
Labels: bug

#757 Various device MPI improvements and fixes for GS auto-tuning
  doc/pages/appendix.md
  src/gs/gather_scatter.f90
Labels: enhancement, GPU, NVIDIA, AMD

#758 Backport shmem opt and fix various bugs in OpenCL schwarz precon.
  src/math/bcknd/device/opencl/schwarz.c
  src/math/bcknd/device/opencl/schwarz_kernel.cl
Labels: bug, enhancement, GPU, OpenCL

#759 Backport shm mem opt in OpenCL fdm
  src/math/bcknd/device/opencl/fdm.c
  src/math/bcknd/device/opencl/fdm_kernel.cl
Labels: enhancement, GPU, OpenCL

#763 Fix SIGUSR and joblimit
  patches/nvhpc_bge.patch
  src/common/jobctrl.f90
  src/common/signal.f90
Labels: enhancement

#764 Feature/read fld files
  src/.depends
  src/Makefile.am
  src/io/file.f90
  src/io/fld_file.f90
  src/io/fld_file_data.f90
Labels: enhancement
