Repository ExtremeFLOW/neko, pull requests merged in 2023-10, with the labels that each got.

#986 modified the intent of coef in _init
  src/io/data_streamer.F90
Labels: compilers, Cray

#987 Fix typo in nvtx interface
  src/device/cuda/nvtx.F90
Labels: bug, NVIDIA

#988 Fix wrapping and expose of Fortran MPI communicator to C/C++ bcknds
  src/Makefile.am
  src/comm/comm.F90.in
  src/comm/comm.h
  src/comm/comm_wrapper.c
  src/comm/parmetis_wrapper.c
  src/gs/bcknd/device/device_mpi.c
  src/math/bcknd/device/device_mpi_reduce.c
  src/math/bcknd/device/device_mpi_reduce.h
Labels: bug, enhancement, compilers, GPU, NVIDIA, AMD, OpenCL

#989 Fix Intel CI
  .github/workflows/develop.yml
Labels: compilers, CI

#990 Fix release CI
  .github/workflows/main.yml
Labels: CI

#980 Throw an error if the re2 file label id is out of range
  src/io/re2_file.f90
Labels: bug

#998 Merge rbc cylinder with probes and expose tensor in neko.f90
  examples/rayleigh-benard-cylinder-probes/README.md
  examples/rayleigh-benard-cylinder-probes/cylinder.nmsh
  examples/rayleigh-benard-cylinder-probes/rayleigh.case
  examples/rayleigh-benard-cylinder-probes/rayleigh.f90
  examples/rayleigh-benard-cylinder/README.md
  examples/rayleigh-benard-cylinder/postprocess_probes.py
  examples/rayleigh-benard-cylinder/probes.csv
  examples/rayleigh-benard-cylinder/rayleigh.case
  examples/rayleigh-benard-cylinder/rayleigh.f90
  src/neko.f90
Labels: case

#999 Time interpolator
  src/.depends
  src/Makefile.am
  src/common/time_interpolator.f90
  src/neko.f90
Labels: enhancement

#994 Dimensional solvers, new material properties input and user hook
  examples/2d_cylinder/2d_cylinder.case
  examples/cyl_boundary_layer/cyl_bl_basic.case
  examples/cyl_boundary_layer/cyl_bl_rot.case
  examples/cyl_boundary_layer/cyl_bl_user.case
  examples/hemi/hemi.case
  examples/lid/lid.case
  examples/lid/lid2d.case
  examples/rayleigh-benard-cylinder/rayleigh.case
  examples/rayleigh-benard-cylinder/rayleigh.f90
  examples/rayleigh-benard/rayleigh.case
  examples/rayleigh-benard/rayleigh.f90
  examples/turb_channel/turb_channel.case
  examples/turbpipe/pipe.case
  examples/turbpipe/pipe_source.case
  reframe/src/minihemi.case.template
  reframe/src/rayleigh.case.template
  reframe/src/rayleigh.f90
  reframe/src/tgv.case.template
  src/.depends
  src/Makefile.am
  src/case.f90
  src/common/material_properties.f90
  src/common/user_intf.f90
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
  src/fluid/bcknd/device/cuda/pnpn_res.cu
  src/fluid/bcknd/device/cuda/prs_res_kernel.h
  src/fluid/bcknd/device/hip/pnpn_res.hip
  src/fluid/bcknd/device/hip/prs_res_kernel.h
  src/fluid/bcknd/device/opencl/pnpn_res.c
  src/fluid/bcknd/device/opencl/pnpn_res_kernel.cl
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/bcknd/sx/pnpn_res_sx.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_volflow.f90
  src/fluid/pnpn_res.f90
  src/scalar/bcknd/cpu/scalar_residual_cpu.f90
  src/scalar/bcknd/device/scalar_residual_device.F90
  src/scalar/bcknd/sx/scalar_residual_sx.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_residual.f90
  src/scalar/scalar_scheme.f90
  src/simulation.f90
Labels: enhancement

#1002 Fix typo, preventing user_pointwise from being selected
  src/fluid/fluid_user_source_term.f90
Labels: bug

#1005 Various fixes for point interpolator
  src/.depends
  src/neko.f90
  src/sem/point_interpolator.f90
Labels: enhancement

#1006 Add method for euclidean distance between two points
  src/mesh/point.f90
Labels: enhancement

#970 A draft for programming conventions and patterns
  doc/Doxyfile.in
  doc/Makefile.am
  doc/pages/dev_patterns.md
  doc/pages/index.md
Labels: documentation

#1004 Enhancement Probes
  doc/pages/simcomps.md
  examples/rayleigh-benard-cylinder/rayleigh.case
  examples/rayleigh-benard-cylinder/rayleigh.f90
  src/.depends
  src/Makefile.am
  src/common/datadist.f90
  src/common/global_interpolation.F90
  src/common/probes.F90
  src/sem/local_interpolation.f90
  src/sem/point_interpolator.f90
  src/simulation_components/probes.F90
  src/simulation_components/simulation_component_factory.f90
Labels: enhancement, refactor
