Repository ExtremeFLOW/neko, pull requests merged in 2024-12, with the labels that each got.

#1627 Fix pressure when no Dirichlet BCs
  src/.depends
  src/bc/bc.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/math/operators.f90
Labels: bug

#1607 Proper usage of intent in solvers
  src/adt/stack.f90
  src/bc/bc.f90
  src/bc/facet_normal.f90
  src/common/bcknd/cpu/rhs_maker_cpu.f90
  src/common/bcknd/device/rhs_maker_device.F90
  src/common/bcknd/sx/rhs_maker_sx.f90
  src/common/rhs_maker.f90
  src/field/mean_field.f90
  src/fluid/advection.f90
  src/fluid/bcknd/advection/adv_dealias.f90
  src/fluid/bcknd/advection/adv_dummy.f90
  src/fluid/bcknd/advection/adv_no_dealias.f90
  src/fluid/bcknd/advection/adv_oifs.f90
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/bcknd/sx/pnpn_res_sx.f90
  src/fluid/fluid_plan1.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_source_term.f90
  src/fluid/fluid_stats.f90
  src/fluid/fluid_user_source_term.f90
  src/fluid/fluid_volflow.f90
  src/fluid/mean_flow.f90
  src/fluid/mean_sqr_flow.f90
  src/fluid/pnpn_res.f90
  src/fluid/stress_formulation/bcknd/cpu/pnpn_res_stress_cpu.f90
  src/fluid/stress_formulation/bcknd/device/pnpn_res_stress_device.F90
  src/krylov/bcknd/cpu/pc_jacobi.f90
  src/krylov/bcknd/device/pc_jacobi_device.F90
  src/krylov/bcknd/sx/pc_jacobi_sx.f90
  src/krylov/pc_hsmg.f90
  src/math/bcknd/cpu/opr_cpu.f90
  src/math/bcknd/cpu/tensor_cpu.f90
  src/math/bcknd/device/opr_device.F90
  src/math/bcknd/sx/opr_sx.f90
  src/math/bcknd/sx/sx_conv1.f90
  src/math/bcknd/sx/tensor_sx.f90
  src/math/bcknd/xsmm/opr_xsmm.F90
  src/math/bcknd/xsmm/tensor_xsmm.F90
  src/math/fdm.f90
  src/math/operators.f90
  src/math/schwarz.f90
  src/math/tensor.f90
  src/scalar/bcknd/cpu/scalar_residual_cpu.f90
  src/scalar/bcknd/device/scalar_residual_device.F90
  src/scalar/bcknd/sx/scalar_residual_sx.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_residual.f90
  src/scalar/scalar_scheme.f90
  src/scalar/scalar_source_term.f90
  src/scalar/scalar_user_source_term.f90
  src/scalar/source_scalar.f90
  src/sem/interpolation.f90
  src/source_terms/boussinesq_source_term.f90
  src/source_terms/brinkman_source_term.f90
  src/source_terms/const_source_term.f90
  src/source_terms/coriolis_source_term.f90
  src/source_terms/source_term.f90
  src/source_terms/source_term_handler.f90
Labels: enhancement

#1631 fix correct dr,ds,dt
  src/simulation_components/derivative.f90
Labels: bug

#1625 Add convergence to the monitor
  doc/pages/user-guide/case-file.md
  src/.depends
  src/fluid/fluid_aux.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/cheby_device.F90
  src/krylov/bcknd/device/fusedcg_cpld_device.F90
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/krylov.f90
Labels: enhancement

#1624 Feature/tamg
  src/.depends
  src/Makefile.am
  src/fluid/fluid_scheme.f90
  src/krylov/pc_hsmg.f90
  src/krylov/precon_fctry.f90
  src/multigrid/phmg.f90
  src/multigrid/tree_amg.f90
  src/multigrid/tree_amg_aggregate.f90
  src/multigrid/tree_amg_multigrid.f90
  src/multigrid/tree_amg_smoother.f90
  src/multigrid/tree_amg_utils.f90
Labels: enhancement

#1616 Warning when performing LES
  src/.depends
  src/fluid/fluid_scheme.f90
  src/les/dynamic_smagorinsky.f90
  src/les/sigma.f90
  src/les/smagorinsky.f90
  src/les/vreman.f90
  src/scalar/scalar_scheme.f90
  src/simulation_components/les_simcomp.f90
Labels: enhancement

#1639 Fix kind value dependent edge index
  src/sem/dofmap.f90
Labels: bug, compilers, NAG

#1640 Fix invalid cast
  src/sem/dofmap.f90
Labels: bug

#1641 Improved bc_list type
  examples/poisson/driver.f90
  src/.depends
  src/Makefile.am
  src/bc/bc.f90
  src/bc/bc_list.f90
  src/bc/field_dirichlet.f90
  src/bc/field_dirichlet_vector.f90
  src/common/projection.f90
  src/common/user_intf.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_volflow.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/cheby_device.F90
  src/krylov/bcknd/device/fusedcg_cpld_device.F90
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/krylov/pc_hsmg.f90
  src/math/schwarz.f90
  src/multigrid/phmg.f90
  src/multigrid/tree_amg.f90
  src/multigrid/tree_amg_multigrid.f90
  src/multigrid/tree_amg_smoother.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1643 Add neko_type_error for reporting invalid type selection
  src/common/utils.f90
Labels: enhancement

#1632 Make both comp. and comm. gs backends selectable
  src/gs/gather_scatter.f90
Labels: enhancement
