Repository ExtremeFLOW/neko, pull requests merged in 2024-09, with the labels that each got.

#1463 fix mistake in simcomp allocation
  src/simulation_components/simcomp_executor.f90
Labels: bug

#1464 Add linting action and create post merge job for develop
  .github/actions/flint/action.yml
  .github/actions/flint/readme.md
  .github/actions/flint/requirements-flint.txt
  .github/workflows/check_lint.yml
  .github/workflows/post_develop.yml
  README.md
Labels: CI

#1473 Fix segv. due to invalid C interface (c_int vs c_size_t)
  src/common/cpuid.c
  src/common/system.f90
Labels: bug

#1467 Collect runtime stats for each profiler region
  doc/pages/user-guide/case-file.md
  src/.depends
  src/Makefile.am
  src/common/profiler.F90
  src/common/projection.f90
  src/common/runtime_statistics.f90
  src/common/sampler.f90
  src/fluid/fluid_pnpn.f90
  src/gs/gather_scatter.f90
  src/krylov/pc_hsmg.f90
  src/neko.f90
  src/scalar/scalar_pnpn.f90
Labels: enhancement, performance

#1477 Fix interface to CrayPat
  src/.depends
  src/common/craypat.F90
  src/common/profiler.F90
Labels: Cray, performance

#1478 Add support for Fujitsu Advanced Performance Profiler
  src/common/profiler.F90
  src/fluid/fluid_pnpn.f90
  src/gs/gather_scatter.f90
  src/krylov/pc_hsmg.f90
  src/scalar/scalar_pnpn.f90
Labels: Fujitsu, performance

#1482 Fix documentation for the pressure solve
  doc/pages/user-guide/case-file.md
Labels: documentation

#1480 Add new JSON array extractor and use it in fluid source term
  src/common/json_utils.f90
  src/fluid/fluid_source_term.f90
Labels: enhancement

#1479 Add new source term functionality
  src/fluid/fluid_source_term.f90
  src/scalar/scalar_source_term.f90
Labels: enhancement

#1483 Add the option of monitoring the residual history from linear solvers
  doc/pages/user-guide/case-file.md
  src/.depends
  src/fluid/fluid_scheme.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/cheby_device.F90
  src/krylov/bcknd/device/fusedcg_cpld_device.F90
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1481 Introduction of source term handler
  src/.depends
  src/Makefile.am
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_source_term.f90
  src/fluid/fluid_user_source_term.f90
  src/scalar/scalar_scheme.f90
  src/scalar/scalar_source_term.f90
  src/scalar/scalar_user_source_term.f90
  src/source_terms/source_term_handler.f90
Labels: enhancement

#1485 Fix warnings with rocm 6.x
  src/common/bcknd/device/hip/projection.hip
  src/krylov/bcknd/device/hip/fusedcg_aux.hip
  src/krylov/bcknd/device/hip/gmres_aux.hip
  src/krylov/bcknd/device/hip/pipecg_aux.hip
  src/math/bcknd/device/hip/ax_helm.hip
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/opr_cdtp.hip
  src/math/bcknd/device/hip/opr_cfl.hip
  src/math/bcknd/device/hip/opr_conv1.hip
  src/math/bcknd/device/hip/opr_dudxyz.hip
  src/math/bcknd/device/hip/opr_lambda2.hip
  src/math/bcknd/device/hip/opr_opgrad.hip
Labels: GPU, AMD

#1465 Move badge creation to checks
  .github/workflows/check_gnu.yml
  .github/workflows/check_intel.yml
  .github/workflows/check_lint.yml
  .github/workflows/check_nvidia.yml
  .github/workflows/develop.yml
  .github/workflows/post_develop.yml
  README.md
Labels: CI

#1491 Fix invalid type in OpenCL argument
  src/math/bcknd/device/opencl/math_kernel.cl
Labels: bug, GPU, OpenCL

#1488 Introduce the device variant of Add4
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/field_math.f90
  src/math/math.f90
Labels: enhancement, GPU, NVIDIA, AMD, OpenCL

#1484 Add overview of the most important types to the docs
  doc/Makefile.am
  doc/pages/developer-guide.md
  doc/pages/developer-guide/important_types.md
Labels: documentation

#1492 Fix regression in OpenCL backend
  src/math/bcknd/device/opencl/cdtp_kernel.cl
  src/math/bcknd/device/opencl/opr_cdtp.c
Labels: bug, GPU, OpenCL

#1493 Add map_2d
  contrib/average_field_in_space/average_field_in_space.f90
  contrib/calc_lift_from_field/calc_lift_from_field.f90
  src/.depends
  src/Makefile.am
  src/io/fld_file_data.f90
  src/neko.f90
  src/sem/map_1d.f90
  src/sem/map_2d.f90
Labels: enhancement

#1502 Add support for NVIDIA Performance Library (NVPL)
  m4/ax_blas.m4
  m4/ax_lapack.m4
Labels: compilers, NVIDIA

#1506 Fix regression (due to swich dc in dofmap loops
  src/sem/dofmap.f90
Labels: bug

#1503 Refactor device math and improve scoping
  src/.depends
  src/Makefile.am
  src/math/bcknd/device/cuda/cuda_math.f90
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/hip_math.f90
  src/math/bcknd/device/opencl/opencl_math.f90
Labels: enhancement, GPU, refactor

#1510 Fix invalid FDM interface for OpenCL
  src/math/bcknd/device/opencl/fdm.c
Labels: bug, GPU, OpenCL

#1497 Purge material_properties_t
  src/.depends
  src/Makefile.am
  src/case.f90
  src/common/material_properties.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
  src/simulation.f90
  src/simulation_components/force_torque.f90
Labels: refactor

#1520 Harmonize dofmap constructor and destructor, bump style
  bench/gs/driver.f90
  bench/nekbone/driver.f90
  contrib/average_field_in_space/average_field_in_space.f90
  contrib/calc_lift_from_field/calc_lift_from_field.f90
  contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90
  examples/poisson/driver.f90
  src/field/field.f90
  src/fluid/fluid_plan1.f90
  src/fluid/fluid_scheme.f90
  src/io/chkp_file.f90
  src/krylov/pc_hsmg.f90
  src/math/schwarz.f90
  src/mesh/point_zone_registry.f90
  src/sem/dofmap.f90
  tests/dofmap/dofmap_parallel.pf
  tests/field/field_parallel.pf
  tests/gather_scatter/gather_scatter_parallel.pf
  tests/point_interpolation/point_interpolation_parallel.pf
  tests/scratch_registry/test_scratch_registry.pf
Labels: refactor

#1521 Check for existence of csv file in `count_lines`
  src/io/csv_file.f90
Labels: bug
