Repository ExtremeFLOW/neko, pull requests merged in 2024-03, with the labels that each got.

#1148 Feature/variable dt
  doc/pages/case-file.md
  src/.depends
  src/Makefile.am
  src/common/time_step_controller.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
  src/simulation.f90
Labels: enhancement

#1165 Fixes crash in scalar when parsin bcs
  src/.depends
  src/scalar/scalar_scheme.f90
Labels: bug

#1014 Lift and drag and 1D GLL point mapping
  configure.ac
  contrib/Makefile.am
  contrib/average_field_in_space/average_field_in_space.f90
  contrib/calc_lift_from_field/Makefile.am
  contrib/calc_lift_from_field/calc_lift_from_field.f90
  src/.depends
  src/Makefile.am
  src/math/math.f90
  src/math/operators.f90
  src/neko.f90
  src/qoi/drag_torque.f90
  src/sem/coef.f90
  src/sem/map_1d.f90
Labels: enhancement

#1168 Remove if-else block to ease vectorisation
  src/math/operators.f90
Labels: performance

#1173 Update projection.f90
  src/common/projection.f90
Labels: bug

#1172 Prevent the develop documentation from running on forks
  .github/workflows/docsdev.yml
Labels: CI

#1145 Fix Vreman model nut computation and improve destructors
  src/les/bcknd/cpu/vreman_cpu.f90
  src/les/vreman.f90
  src/simulation_components/les_simcomp.f90
Labels: bug

#1176 Update for new gh actions
  .github/workflows/develop.yml
Labels: CI

#1179 Fix invalid CFL calculation using CCE
  src/math/operators.f90
Labels: bug, compilers, Cray

#1180 Add doc for output_boundary
  doc/pages/case-file.md
Labels: documentation

#1182 Updates to the gitignore
  .gitignore
Labels: enhancement

#1184 Fix mistake in cylindrical point zone
  src/mesh/point_zones/cylinder_point_zone.f90
Labels: bug

#1183 Average fields in two directions
  contrib/average_field_in_space/average_field_in_space.f90
  examples/turb_channel/README.md
  src/neko.f90
  src/sem/map_1d.f90
Labels: enhancement

#1163 Add support for hex objects
  src/.depends
  src/common/json_utils.f90
  src/math/signed_distance.f90
  src/mesh/search_tree/aabb.f90
  src/source_terms/brinkman_source_term.f90
Labels: enhancement

#1191 Disable CI checks on drafts.
  .github/workflows/develop.yml
Labels: CI

#1192 Add field_writer simcomp
  doc/pages/simcomps.md
  src/.depends
  src/Makefile.am
  src/field/field_list.f90
  src/field/field_registry.f90
  src/neko.f90
  src/simulation_components/field_writer.f90
  src/simulation_components/simulation_component_factory.f90
Labels: enhancement

#1195 F2py coupling
  src/io/data_streamer.F90
  src/io/nek_adios2.cpp
Labels: refactor

#1194 Update example for new ksp interface
  examples/poisson/driver.f90
Labels: bug

#1198 debug on projection
  src/fluid/fluid_pnpn.f90
  src/scalar/scalar_pnpn.f90
Labels: bug

#1199 Ensure bc_inflow is allocated before resolving its type
  src/fluid/fluid_scheme.f90
Labels: bug

#1197 Fix dangling pointers
  makeneko.in
  src/fluid/fluid_plan1.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/mesh/point_zone_registry.f90
  src/simulation.f90
  src/simulation_components/simcomp_executor.f90
Labels: bug, compilers

#1187 Point interpolation test
  tests/point_interpolation/point_interpolation_parallel.pf
Labels: enhancement

#1196 Enhancement/boundary_mesh_transform
  doc/pages/case-file.md
  examples/immersed_bunny/immersed_bunny.case
  examples/immersed_bunny/run.sh
  src/.depends
  src/common/json_utils.f90
  src/math/signed_distance.f90
  src/mesh/aabb_tree.f90
  src/mesh/search_tree/aabb.f90
  src/mesh/tri_mesh.f90
  src/source_terms/brinkman_source_term.f90
Labels: enhancement

#1200 Use field_writer in lambda2 and vorticity
  src/.depends
  src/simulation_components/lambda2.f90
  src/simulation_components/vorticity.f90
Labels: enhancement

#1201 Cleanup dead code
  src/common/projection.f90
Labels: enhancement

#1202 Fix possible dis-cont. warnings
  src/adt/stack.f90
  src/gs/gather_scatter.f90
  src/mesh/mesh.f90
  src/sem/map_1d.f90
Labels: compilers, NAG, performance

#1208 Try to fix Intel CI
  .github/workflows/develop.yml
Labels: CI

#1206 Fix danling pointers in mesh
  src/io/nmsh_file.f90
  src/mesh/mesh.f90
Labels: bug

#1211 Use proper abscmp to check for 0.0_rp
  src/.depends
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
Labels: bug
