Repository ExtremeFLOW/neko, pull requests merged in 2024-02, with the labels that each got.

#1120 Update pyNeko interface for new JSON based workflow
  contrib/pyneko/Makefile.am
  contrib/pyneko/examples/hemi/hemi.py
  contrib/pyneko/pyNeko/__init__.py
  contrib/pyneko/pyNeko/case.py
  contrib/pyneko/src/Makefile.am
  contrib/pyneko/src/json_case.f90
  contrib/pyneko/src/neko_intf.f90
  src/case.f90
Labels: enhancement

#1126 Fix field allocation in fld_field_output
  src/io/fld_file_output.f90
Labels: bug

#1128 Add helper to extract json array items as json objects
  src/common/json_utils.f90
Labels: enhancement

#1125 Add start and end time for source addition, update documentation
  doc/pages/case-file.md
  src/fluid/fluid_source_term.f90
  src/fluid/fluid_user_source_term.f90
  src/scalar/scalar_source_term.f90
  src/scalar/scalar_user_source_term.f90
  src/source_terms/const_source_term.f90
  src/source_terms/source_term.f90
Labels: enhancement

#1131 Slight addition to stack
  src/adt/stack.f90
Labels: enhancement

#1134 Add basic documenation on IO file formats
  doc/Doxyfile.in
  doc/pages/io.md
Labels: documentation

#1132 Init simcomps according to order parameter
  src/simulation_components/simcomp_executor.f90
Labels: enhancement

#1136 Check if the file exists
  src/.depends
  src/io/chkp_file.f90
  src/io/csv_file.f90
  src/io/fld_file.f90
  src/io/generic_file.f90
  src/io/map_file.f90
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/io/rea_file.f90
  src/io/stl_file.f90
  src/io/vtk_file.f90
Labels: bug

#1139 Docstrings, and "only" for operators
  src/math/operators.f90
Labels: documentation, refactor

#1149 Updated point zone initialization
  src/case.f90
  src/mesh/point_zone_registry.f90
Labels: refactor

#1146 Fix fld reader
  src/io/fld_file.f90
Labels: bug

#1152 Addition of new point zone type: Cylinder.
  doc/pages/case-file.md
  doc/pages/point-zones.md
  src/.depends
  src/Makefile.am
  src/mesh/point_zone_factory.f90
  src/mesh/point_zones/cylinder_point_zone.f90
Labels: enhancement

#1153 Add possibility to provide default string for json string array reader
  src/common/json_utils.f90
Labels: enhancement

#1156 fix/pfunit
  tests/device/device.pf
  tests/point_interpolation/point_interpolation_parallel.pf
Labels: bug, GPU

#1150 Fix bc_label loop in scalar_scheme_t
  src/scalar/scalar_scheme.f90
Labels: bug

#1161 Update nvhpc to 24.1
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: CI
