Repository ExtremeFLOW/neko, pull requests merged in 2024-07, with the labels that each got.

#1326 Add interface for coupled solve
  doc/pages/user-guide/case-file.md
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/fluid/fluid_pnpn.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/cuda/fusedcg_cpld_aux.cu
  src/krylov/bcknd/device/cuda/fusedcg_cpld_kernel.h
  src/krylov/bcknd/device/fusedcg_cpld_device.F90
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/math/bcknd/device/ax_helm_device.F90
  src/math/bcknd/device/cuda/ax_helm.cu
  src/math/bcknd/device/cuda/ax_helm_kernel.h
  src/math/bcknd/device/hip/ax_helm.hip
  src/math/bcknd/device/hip/ax_helm_kernel.h
Labels: GPU, NVIDIA, AMD, performance

#1185 User-created simcomps
  doc/Doxyfile.in
  doc/examples/simulation_components/user_simcomp.case
  doc/examples/simulation_components/user_simcomp.f90
  doc/pages/user-guide/simcomps.md
  doc/pages/user-guide/user-file.md
  src/.depends
  src/common/user_intf.f90
  src/neko.f90
  src/simulation.f90
  src/simulation_components/simcomp_executor.f90
  src/simulation_components/simulation_component.f90
  src/simulation_components/simulation_component_fctry.f90
Labels: enhancement

#1319 Feature/math_field
  src/.depends
  src/Makefile.am
  src/field/mean_field.f90
  src/math/bcknd/field_math.f90
  src/source_terms/bcknd/cpu/brinkman_source_term_cpu.f90
  src/source_terms/bcknd/device/brinkman_source_term_device.f90
  src/source_terms/brinkman_source_term.f90
Labels: enhancement

#1294 Linting update: Boost score and adjust rules.
  .github/workflows/check_lint.yml
  .github/workflows/develop.yml
  flinter_rc.yml
Labels: CI

#1337 Add line length check and adjust repository wide linting requirement
  .github/workflows/develop.yml
  flinter_rc.yml
Labels: CI

#1336 Fix/device_count
  src/device/cuda_intf.F90
  src/device/hip_intf.F90
  src/device/opencl_intf.F90
Labels: NVIDIA, AMD, OpenCL

#1330 Residual kernels for the full viscous stress formulation
  src/.depends
  src/Makefile.am
  src/fluid/stress_formulation/bcknd/cpu/pnpn_res_stress_cpu.f90
  src/fluid/stress_formulation/bcknd/device/cuda/pnpn_stress_res.cu
  src/fluid/stress_formulation/bcknd/device/cuda/prs_stress_res_kernel.h
  src/fluid/stress_formulation/bcknd/device/pnpn_res_stress_device.F90
  src/fluid/stress_formulation/pnpn_res_stress.f90
  src/fluid/stress_formulation/pnpn_res_stress_fctry.f90
Labels: enhancement

#1340 Add call to missing HIP kernel
  src/math/bcknd/device/ax_helm_device.F90
Labels: enhancement, GPU, AMD

#1341 Fixed invalid/assumed lower bound error with NAG
  src/wall_models/wall_model.f90
Labels: bug, compilers, NAG

#1345 Fix global requirement for changed files
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: bug, CI

#1342 fix the amplitude of the 3D TS waves to match the Schlatter 2005 case
  examples/TS_channel/TS_channel.f90
  examples/TS_channel/plot_modes.ipynb
Labels: case

#1324 Doc/fix user file typo
  doc/pages/appendices.md
  doc/pages/developer-guide/accelerators.md
  doc/pages/developer-guide/code-style.md
  doc/pages/developer-guide/dev_patterns.md
  doc/pages/developer-guide/testing.md
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/io.md
  doc/pages/user-guide/point-zones.md
  doc/pages/user-guide/simcomps.md
  doc/pages/user-guide/user-file.md
  examples/cyl_boundary_layer/cyl_bl.f90
  examples/cyl_boundary_layer/cyl_bl_user_bc_test.case
Labels: documentation

#1350 Fix broken links in documentation
  doc/pages/user-guide/user-file.md
Labels: documentation

#1354 Fix missing set_coef call for user inflow condition
  flinter_rc.yml
  src/bc/usr_inflow.f90
Labels: bug

#1360 Fix logic in csv_reader to correctly read headers
  src/io/csv_file.f90
Labels: bug

#1367 Add coupled cg solver for CPU
  doc/pages/user-guide/case-file.md
  src/.depends
  src/Makefile.am
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/krylov/krylov_fctry.f90
Labels: enhancement

#1352 updated the initial condtion for channel flow example
  examples/turb_channel/turb_channel.case
  examples/turb_channel/turb_channel.f90
Labels: case

#1379 Fix/flint_loophole
  .github/workflows/check_lint.yml
Labels: bug, CI

#1383 Update code style documentation
  .github/workflows/develop.yml
  doc/pages/developer-guide/code-style.md
  flinter_rc.yml
Labels: documentation

#1390 Fix "#endif" bug and disable double spacing rule
  flinter_rc.yml
Labels: bug, CI

#1388 performance fix in gmres
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/device/gmres_device.F90
Labels: performance

#1389 Missing stack init in overlap computation
  src/mesh/aabb_tree.f90
Labels: bug

#1394 Fix bug in probes and wrong documentation
  doc/pages/user-guide/simcomps.md
  src/simulation_components/probes.F90
Labels: bug

#1387 Add logical operators and combine point zones
  doc/pages/user-guide/point-zones.md
  src/.depends
  src/Makefile.am
  src/mesh/point_zone.f90
  src/mesh/point_zone_fctry.f90
  src/mesh/point_zone_registry.f90
  src/mesh/point_zones/box_point_zone.f90
  src/mesh/point_zones/combine_point_zone.f90
  src/mesh/point_zones/cylinder_point_zone.f90
  src/mesh/point_zones/sphere_point_zone.f90
Labels: enhancement

#1385 Add full stress tensor and LES capability to fluid
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/case.f90
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
  src/fluid/bcknd/device/pnpn_res_device.F90
  src/fluid/bcknd/sx/pnpn_res_sx.f90
  src/fluid/fluid_aux.f90
  src/fluid/fluid_fctry.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/pnpn_res.f90
  src/fluid/stress_formulation/bcknd/cpu/pnpn_res_stress_cpu.f90
  src/fluid/stress_formulation/bcknd/device/cuda/pnpn_stress_res.cu
  src/fluid/stress_formulation/bcknd/device/cuda/prs_stress_res_kernel.h
  src/fluid/stress_formulation/bcknd/device/pnpn_res_stress_device.F90
  src/fluid/stress_formulation/pnpn_res_stress.f90
  src/fluid/stress_formulation/pnpn_res_stress_fctry.f90
  src/krylov/krylov_fctry.f90
  src/les/dynamic_smagorinsky.f90
  src/les/les_model.f90
  src/les/sigma.f90
  src/les/smagorinsky.f90
  src/les/vreman.f90
  src/math/ax_helm_full.f90
  src/math/operators.f90
  src/scalar/scalar_scheme.f90
  src/simulation_components/les_simcomp.f90
  src/simulation_components/simcomp_executor.f90
Labels: enhancement

#1399 Improve vectorisation of cpld cg
  src/krylov/bcknd/cpu/cg_coupled.f90
Labels: compilers, Fujitsu

#1401 Change to latest nvhpc
  .github/workflows/check_nvidia.yml
Labels: CI

#1400 Remove redudant array in gmres (cpu)
  src/krylov/bcknd/cpu/gmres.f90
Labels: performance
