Repository ExtremeFLOW/neko, pull requests merged in 2024-04, with the labels that each got.

#1209 Fix bug in reading type from json file
  src/source_terms/brinkman_source_term.f90
Labels: bug

#1221 Fix invalid, expensive sync in gmres
  src/krylov/bcknd/device/gmres_device.F90
Labels: GPU, AMD, performance

#1223 Add a wrapper for dofmap%size in the field_t type
  src/field/field.f90
Labels: enhancement

#1220 Remove unused shmem variable
  src/math/bcknd/device/cuda/cdtp_kernel.h
  src/math/bcknd/device/hip/cdtp_kernel.h
Labels: GPU, NVIDIA, AMD

#1171 Refactor pc_jacobi (CPU) to allow for vectorisation
  src/krylov/bcknd/cpu/pc_jacobi.f90
Labels: refactor, performance

#1222 Introduce probe header and update probe documentation
  doc/pages/simcomps.md
  src/simulation_components/probes.F90
Labels: enhancement

#985 Feature user dirichlet bcs
  doc/pages/case-file.md
  doc/pages/user-file.md
  examples/cyl_boundary_layer/cyl_bl.f90
  examples/cyl_boundary_layer/cyl_bl_user_bc_test.case
  src/.depends
  src/Makefile.am
  src/bc/bc.f90
  src/bc/field_dirichlet.f90
  src/bc/field_dirichlet_vector.f90
  src/case.f90
  src/common/user_intf.f90
  src/common/utils.f90
  src/field/field_registry.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/math.f90
  src/mesh/mesh.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1218 fix bugs in average_field_in_space: allow avg on multiple time steps
  contrib/average_field_in_space/average_field_in_space.f90
Labels: bug

#1213 Modernize advection types to use json
  src/.depends
  src/Makefile.am
  src/fluid/advection.f90
  src/fluid/advection_fctry.f90
  src/fluid/fluid_pnpn.f90
  src/scalar/scalar_pnpn.f90
Labels: enhancement

#1216 Remove u, v, w fron Dong outflow constructor
  src/bc/dong_outflow.f90
  src/bc/symmetry.f90
  src/fluid/fluid_scheme.f90
Labels: refactor

#1224 Restructure lambda2 routine, and fix calculation on SX
  .github/workflows/develop.yml
  src/.depends
  src/Makefile.am
  src/math/bcknd/cpu/opr_cpu.f90
  src/math/bcknd/sx/opr_sx.f90
  src/math/bcknd/sx/sx_lambda2.f90
  src/math/operators.f90
Labels: bug, SX, refactor

#1225 Updated cff file to include all authors
  CITATION.cff
Labels: documentation

#1227 Update publist
  README.md
  doc/pages/publication-list.md
Labels: documentation

#1230 Remove explicit mention of KTH
  README.md
  doc/pages/index.md
Labels: documentation

#1231 Fix issues in OpenCL backends when compiling with recent clang
  src/device/opencl/check.c
  src/device/opencl/jit.c
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/opr_cfl.c
  src/math/bcknd/device/opencl/opr_opgrad.c
Labels: bug, compilers, GPU, OpenCL

#1232 Fix math rendering for Brinkmann source term
  doc/pages/case-file.md
Labels: documentation

#1235 Reformat documentation and contributing guide
  doc/Doxyfile.in
  doc/Makefile.am
  doc/pages/appendices.md
  doc/pages/appendices/governing-equations.md
  doc/pages/appendices/publications.md
  doc/pages/appendix.md
  doc/pages/developer-guide.md
  doc/pages/developer-guide/accelerators.md
  doc/pages/developer-guide/code-style.md
  doc/pages/developer-guide/contributing.md
  doc/pages/developer-guide/dev_patterns.md
  doc/pages/developer-guide/testing.md
  doc/pages/index.md
  doc/pages/user-guide.md
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/installation.md
  doc/pages/user-guide/io.md
  doc/pages/user-guide/point-zones.md
  doc/pages/user-guide/simcomps.md
  doc/pages/user-guide/statistics-guide.md
  doc/pages/user-guide/user-file.md
Labels: documentation

#1238 Backport manual fixes from release/0.8
  doc/Doxyfile.in
  doc/Makefile.am
  doc/pages/appendices.md
  doc/pages/appendices/governing-equations.md
  doc/pages/appendices/publications.md
  doc/pages/appendix.md
  doc/pages/developer-guide.md
  doc/pages/developer-guide/accelerators.md
  doc/pages/developer-guide/code-style.md
  doc/pages/developer-guide/contributing.md
  doc/pages/developer-guide/dev_patterns.md
  doc/pages/developer-guide/testing.md
  doc/pages/index.md
  doc/pages/user-guide.md
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/installation.md
  doc/pages/user-guide/io.md
  doc/pages/user-guide/point-zones.md
  doc/pages/user-guide/simcomps.md
  doc/pages/user-guide/statistics-guide.md
  doc/pages/user-guide/user-file.md
Labels: documentation

#1242 Change to latest rocm
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: CI

#1245 Make probe length consistent for set/get/remove
  src/adt/htable.f90
Labels: enhancement, performance

#1241 Fix detection of libsci for CPE 23.12
  m4/ax_cray.m4
Labels: compilers, Cray

#1246 Add marker for serial files, and fix deadlock
  src/io/file.f90
  src/io/generic_file.f90
Labels: bug

#1247 Add missing call to padded version of Axhelm
  src/math/bcknd/device/cuda/ax_helm.cu
Labels: bug, GPU, NVIDIA, performance

#1248 Cleanup pnpn res device from invalid chars...
  src/fluid/bcknd/device/pnpn_res_device.F90
Labels: bug

#1249 modify apply_vector to account for optional args
  src/bc/field_dirichlet_vector.f90
Labels: bug

#1240 Boundary condition type updates
  src/.depends
  src/bc/bc.f90
  src/bc/bcknd/device/device_inhom_dirichlet.F90
  src/bc/blasius.f90
  src/bc/dirichlet.f90
  src/bc/dong_outflow.f90
  src/bc/facet_normal.f90
  src/bc/field_dirichlet.f90
  src/bc/field_dirichlet_vector.f90
  src/bc/inflow.f90
  src/bc/neumann.f90
  src/bc/non_normal.f90
  src/bc/symmetry.f90
  src/bc/usr_inflow.f90
  src/bc/usr_scalar.f90
  src/bc/wall.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/krylov/pc_hsmg.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1256 Update for latest bc interface
  examples/poisson/driver.f90
Labels: bug

#1257 Fix invalid conversion when naming members of a field series
  src/field/field_series.f90
Labels: bug

#1258 Add div and grad operators
  src/.depends
  src/math/operators.f90
Labels: enhancement

#1260 HDF5 Support
  configure.ac
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/installation.md
  m4/ax_cray.m4
  m4/ax_hdf5.m4
  src/.depends
  src/Makefile.am
  src/case.f90
  src/field/field_series.f90
  src/io/chkp_output.f90
  src/io/file.f90
  src/io/hdf5_file.F90
  src/simulation.f90
Labels: enhancement

#1263 Add missing logic for
  Makefile.am
  configure.ac
Labels: bug

#1254 README with JSON-Fortran
  README.md
Labels: documentation, enhancement
