Repository ExtremeFLOW/neko, pull requests merged in 2024-11, with the labels that each got.

#1575 Add MPI support to mesh checker
  contrib/mesh_checker/mesh_checker.f90
Labels: enhancement

#1555 Spectral error indicator as simcomp
  doc/pages/user-guide/simcomps.md
  src/.depends
  src/Makefile.am
  src/neko.f90
  src/simulation_components/simulation_component_fctry.f90
  src/simulation_components/spectral_error.f90
Labels: enhancement

#1578 Add support for building shared/dynamic libraries
  .gitignore
  Makefile.am
  configure.ac
  contrib/average_field_in_space/Makefile.am
  contrib/average_fields_in_time/Makefile.am
  contrib/calc_lift_from_field/Makefile.am
  contrib/genmeshbox/Makefile.am
  contrib/map_to_equidistant_1d/Makefile.am
  contrib/mesh_checker/Makefile.am
  contrib/postprocess_fluid_stats/Makefile.am
  contrib/prepart/Makefile.am
  contrib/rea2nbin/Makefile.am
  doc/pages/user-guide/installation.md
  regen.sh
  src/.depends
  src/.depends_device
  src/.depends_turboneko
  src/Makefile.am
  tests/unit/bc/Makefile.in
  tests/unit/device/Makefile.in
  tests/unit/device_math/Makefile.in
  tests/unit/device_mathops/Makefile.in
  tests/unit/dofmap/Makefile.in
  tests/unit/fast3d/Makefile.in
  tests/unit/field/Makefile.in
  tests/unit/gather_scatter/Makefile.in
  tests/unit/hex/Makefile.in
  tests/unit/htable/Makefile.in
  tests/unit/jobctrl/Makefile.in
  tests/unit/krylov/Makefile.in
  tests/unit/math/Makefile.in
  tests/unit/mathops/Makefile.in
  tests/unit/matrix/Makefile.in
  tests/unit/mean_field/Makefile.in
  tests/unit/mean_sqr_field/Makefile.in
  tests/unit/mesh/Makefile.in
  tests/unit/octree/Makefile.in
  tests/unit/point/Makefile.in
  tests/unit/point_interpolation/Makefile.in
  tests/unit/quad/Makefile.in
  tests/unit/scratch_registry/Makefile.in
  tests/unit/signal/Makefile.in
  tests/unit/space/Makefile.in
  tests/unit/stack/Makefile.in
  tests/unit/tet/Makefile.in
  tests/unit/time_based_controller/Makefile.in
  tests/unit/time_scheme/Makefile.in
  tests/unit/time_scheme_controller/Makefile.in
  tests/unit/tri/Makefile.in
  tests/unit/tuple/Makefile.in
  tests/unit/uset/Makefile.in
  tests/unit/vector/Makefile.in
Labels: enhancement, compilers, refactor

#1559 Improvements to simulation components
  doc/pages/user-guide/simcomps.md
  src/simulation_components/simcomp_executor.f90
  src/simulation_components/simulation_component.f90
Labels: enhancement

#1565 Fix invalid access to unallocated components of a case
  src/simulation.f90
Labels: bug

#1596 Fix proper usage of intent in Krylov solvers
  src/bc/bc.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/cheby_device.F90
  src/krylov/bcknd/device/fusedcg_cpld_device.F90
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
Labels: enhancement

#1541 Add option to create aabb tree directly from aabb and fix sorting bug
  src/mesh/aabb_tree.f90
  src/mesh/search_tree/aabb.f90
Labels: bug, enhancement

#1601 Fix/error on missing file
  src/case.f90
Labels: bug

#1604 Enhance/cfl deviation tol
  doc/pages/user-guide/case-file.md
  src/common/time_step_controller.f90
Labels: enhancement

#1540 Update to latest nvhpc (24.11)
  .github/workflows/check_nvidia.yml
  .github/workflows/develop.yml
Labels: CI

#1605 nvhpc: workaround for submodule bug
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/krylov/precon.f90
  src/krylov/precon_fctry.f90
  src/les/les_model.f90
  src/les/les_model_fctry.f90
  src/wall_models/wall_model.f90
  src/wall_models/wall_model_fctry.f90
Labels: compilers

#1609 Allow parsing of regular JSON files
  src/neko.f90
Labels: enhancement, case

#1619 Update CITATION.cff
  CITATION.cff
Labels: documentation

#1621 Update case-file.md
  doc/pages/user-guide/case-file.md
Labels: documentation
