Repository ExtremeFLOW/neko, pull requests merged in 2024-01, with the labels that each got.

#1096 Update fluid_volflow.f90
  src/fluid/fluid_volflow.f90
Labels: bug

#1097 Fix a segmentation fault.
  src/simulation_components/simulation_component_factory.f90
Labels: bug

#1098 Feature/metadata in fldfile
  examples/rayleigh-benard-cylinder/rayleigh.f90
  src/.depends
  src/io/fld_file.f90
  src/math/math.f90
Labels: enhancement

#1085 Add support for double precision `fld` files output
  doc/pages/case-file.md
  doc/pages/simcomps.md
  src/.depends
  src/case.f90
  src/common/sampler.f90
  src/io/file.f90
  src/io/fluid_output.f90
  src/io/output.f90
Labels: enhancement, case

#1102 Fix ROCm detection on Cray EX platforms for none HPE provided modules
  m4/ax_cray.m4
Labels: bug, compilers, GPU, Cray, AMD

#1101 Fused CG for CUDA/HIP
  doc/pages/case-file.md
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/krylov/bcknd/device/cuda/fusedcg_aux.cu
  src/krylov/bcknd/device/cuda/fusedcg_kernel.h
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/hip/fusedcg_aux.hip
  src/krylov/bcknd/device/hip/fusedcg_kernel.h
  src/krylov/krylov_fctry.f90
Labels: enhancement, GPU, NVIDIA, AMD, performance

#1077 Add max_iter as component to the krylov type
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/fusedcg_device.F90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/device/pipecg_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/krylov/pc_hsmg.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement, refactor

#1107 Update fld_file.f90
  src/io/fld_file.f90
Labels: bug

#1103 Fix invalid starting residual for (device) pipecg
  src/krylov/bcknd/device/pipecg_device.F90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
Labels: bug, GPU, NVIDIA, AMD, OpenCL

#1108 Fixed regression in gmres (max_iter)
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/sx/gmres_sx.f90
Labels: bug, SX, GPU

#1112 Update map_to_equidistant_1d.f90
  contrib/map_to_equidistant_1d/map_to_equidistant_1d.f90
Labels: bug

#1110 Add advecting cone example
  examples/advecting_cone/.gitignore
  examples/advecting_cone/README.md
  examples/advecting_cone/advecting_cone.case
  examples/advecting_cone/advecting_cone.f90
  examples/advecting_cone/box.nmsh
  examples/advecting_cone/change_order.py
  examples/advecting_cone/create_probes.py
  examples/advecting_cone/results.png
  examples/advecting_cone/run.sh
Labels: new case
