Repository ExtremeFLOW/neko, pull requests merged in 2024-08, with the labels that each got.

#1413 Fix/flinter assignment rule
  flinter_rc.yml
Labels: CI

#1414 Feature/cheby
  src/.depends
  src/Makefile.am
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/krylov_fctry.f90
Labels: enhancement

#1415 Add missing hooks for calling cheby init
  src/krylov/krylov_fctry.f90
Labels: bug

#1416 Use the max_iter if passed in during solve
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/krylov/bcknd/cpu/cheby.f90
Labels: enhancement

#1417 Add a naive device version of cheby
  src/.depends
  src/Makefile.am
  src/krylov/bcknd/device/cheby_device.F90
  src/krylov/krylov_fctry.f90
Labels: enhancement, GPU, NVIDIA, AMD, OpenCL

#1419 Add enforcement of `only` specifications.
  doc/pages/developer-guide/dev_patterns.md
  flinter_rc.yml
Labels: CI

#1425 Added command to install flint and execute it
  doc/pages/developer-guide/code-style.md
Labels: documentation

#1426 Optimize linter execution
  .github/workflows/develop.yml
Labels: CI

#1381 Output the commands used with genmeshbox in a separate log file
  contrib/genmeshbox/genmeshbox.f90
Labels: enhancement

#1429 Fix false restriction on the word "use"
  flinter_rc.yml
Labels: CI

#1431 Fixed dangling pointers
  src/.depends
  src/bc/non_normal.f90
  src/bc/symmetry.f90
  src/fluid/fluid_user_source_term.f90
  src/fluid/fluid_volflow.f90
  src/io/stl_file.f90
  src/mesh/tri_mesh.f90
  src/scalar/scalar_source_term.f90
  src/scalar/scalar_user_source_term.f90
  src/simulation_components/probes.F90
  src/source_terms/boussinesq_source_term.f90
  src/source_terms/brinkman_source_term.f90
  src/source_terms/const_source_term.f90
  src/source_terms/source_term.f90
Labels: bug, compilers, NAG

#1432 Fix danling pointers in fluid and stats
  src/.depends
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_stats.f90
  src/fluid/mean_flow.f90
Labels: bug, NAG

#1422 Fix the linter issue by only checking full words matching `structs`
  flinter_rc.yml
Labels: CI

#1376 Add generic vector/matrix operations
  configure.ac
  src/.depends
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/math.f90
  src/math/matrix.f90
  src/math/vector.f90
  tests/Makefile.am
  tests/matrix/Makefile.in
  tests/matrix/matrix_parallel.pf
  tests/matrix/matrix_test
  tests/vector/vector_parallel.pf
Labels: enhancement, GPU, NVIDIA, AMD, OpenCL

#1435 Make fluid scheme private
  src/.depends
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
Labels: enhancement

#1437 Fix invalid module dependencies
  src/.depends
  src/case.f90
  src/fluid/fluid_pnpn.f90
  src/neko.f90
  src/simulation.f90
Labels: enhancement

#1442 Move factories to submodules
  .github/workflows/develop.yml
  src/.depends
  src/case.f90
  src/common/rhs_maker.f90
  src/common/rhs_maker_fctry.f90
  src/fluid/advection.f90
  src/fluid/advection_fctry.f90
  src/fluid/fluid_fctry.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_source_term.f90
  src/fluid/pnpn_res.f90
  src/fluid/pnpn_res_fctry.f90
  src/fluid/stress_formulation/pnpn_res_stress_fctry.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/krylov/pc_hsmg.f90
  src/krylov/precon.f90
  src/krylov/precon_fctry.f90
  src/les/les_model.f90
  src/les/les_model_fctry.f90
  src/math/ax.f90
  src/math/ax_helm_fctry.f90
  src/math/mathops.f90
  src/mesh/point_zone.f90
  src/mesh/point_zone_fctry.f90
  src/mesh/point_zone_registry.f90
  src/mesh/point_zones/combine_point_zone.f90
  src/neko.f90
  src/qoi/drag_torque.f90
  src/scalar/bcknd/cpu/scalar_residual_cpu.f90
  src/scalar/bcknd/device/scalar_residual_device.F90
  src/scalar/bcknd/sx/scalar_residual_sx.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_residual.f90
  src/scalar/scalar_residual_fctry.f90
  src/scalar/scalar_scheme.f90
  src/scalar/scalar_source_term.f90
  src/simulation_components/les_simcomp.f90
  src/simulation_components/simcomp_executor.f90
  src/simulation_components/simulation_component.f90
  src/simulation_components/simulation_component_fctry.f90
  src/source_terms/source_term.f90
  src/source_terms/source_term_fctry.f90
  src/wall_models/wall_model.f90
  src/wall_models/wall_model_fctry.f90
  tests/mathops/mathops.pf
Labels: enhancement

#1448 Update linting process
  .github/workflows/check_lint.yml
  .github/workflows/develop.yml
Labels: CI

#1375 Feature/Device count
  src/device/cuda_intf.F90
  src/device/device.F90
  src/device/hip_intf.F90
  src/device/opencl_intf.F90
  src/neko.f90
Labels: enhancement, GPU

#1450 Fix missing json symbols
  Makefile.am
  src/.depends
  src/neko.f90
Labels: bug

#1458 Add single element version of cpu conv1 and opgrad to ease future omp work
  src/math/bcknd/cpu/cpu_conv1.f90
  src/math/bcknd/cpu/cpu_opgrad.f90
Labels: enhancement, OpenMP, performance

#1453 Not recomputing integration weights in cdtp
  src/.depends
  src/math/bcknd/cpu/cpu_cdtp.f90
  src/math/bcknd/cpu/opr_cpu.f90
  src/math/bcknd/device/cuda/cdtp_kernel.h
  src/math/bcknd/device/cuda/opr_cdtp.cu
  src/math/bcknd/device/hip/cdtp_kernel.h
  src/math/bcknd/device/hip/opr_cdtp.hip
  src/math/bcknd/device/opr_device.F90
  src/math/operators.f90
Labels: help wanted

#1459 Add enable/disable flags for OpenMP to configure
  configure.ac
  doc/pages/user-guide/installation.md
  m4/ax_openmp.m4
Labels: enhancement, compilers, OpenMP

#1460 Improve vectorisation in projection (CPU)
  src/.depends
  src/common/bcknd/device/device_projection.F90
  src/common/projection.f90
Labels: compilers, performance

#1461 Rewrite loops in dofmap to allow for vectorisation
  src/sem/dofmap.f90
Labels: compilers, performance

#1462 Rework loops to allow vectorisation
  src/.depends
  src/fluid/bcknd/advection/adv_dealias.f90
  src/fluid/fluid_volflow.f90
  src/gs/gs_mpi.f90
  src/les/bcknd/cpu/dynamic_smagorinsky_cpu.f90
  src/les/bcknd/cpu/sigma_cpu.f90
  src/les/bcknd/cpu/smagorinsky_cpu.f90
  src/les/bcknd/cpu/vreman_cpu.f90
  src/sem/bcknd/device/device_coef.F90
  src/sem/coef.f90
Labels: compilers, performance
