Repository ExtremeFLOW/neko, pull requests merged in 2024-05, with the labels that each got.

#1267 Reduce the risk of memory issues in mark zones from list
  src/bc/bc.f90
Labels: bug

#1276 Fix invalid logic, preventing contrib from being built
  configure.ac
Labels: bug

#1261 Slight update to field_dirichlet bcs
  doc/pages/user-guide/case-file.md
  src/bc/field_dirichlet.f90
  src/bc/field_dirichlet_vector.f90
  src/field/field_list.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/neko.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1281 Add back top level contrib guide such that GH is more happy.
  CONTRIBUTING.md
Labels: documentation

#1280 Fix/rocm_version
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: bug, AMD

#1278 Refactor/advection
  src/.depends
  src/Makefile.am
  src/fluid/advection.f90
  src/fluid/advection_fctry.f90
  src/fluid/bcknd/advection/adv_dealias.f90
  src/fluid/bcknd/advection/adv_no_dealias.f90
  src/fluid/fluid_pnpn.f90
  src/scalar/scalar_pnpn.f90
Labels: refactor

#1286 Fix invalid dimension specification (overriden by array declaration)
  src/math/bcknd/cpu/opgrad.f90
  src/math/bcknd/sx/sx_lambda2.f90
  src/math/bcknd/sx/sx_opgrad.f90
Labels: bug, compilers, SX, NAG

#1285 Correctly report compiler vendor for flang
  m4/ax_compiler_vendor.m4
Labels: compilers

#1288 Cleanup unused variables
  src/bc/neumann.f90
  src/bc/non_normal.f90
  src/bc/symmetry.f90
  src/bc/usr_scalar.f90
  src/case.f90
  src/common/log.f90
  src/field/field_list.f90
  src/fluid/flow_ic.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_source_term.f90
  src/fluid/fluid_volflow.f90
  src/io/csv_file.f90
  src/io/fld_file.f90
  src/io/re2_file.f90
  src/krylov/pc_hsmg.f90
  src/les/les_model.f90
  src/math/bcknd/cpu/opr_cpu.f90
  src/math/bcknd/sx/opr_sx.f90
  src/math/bcknd/sx/sx_cfl.f90
  src/math/bcknd/sx/sx_conv1.f90
  src/math/bcknd/sx/sx_lambda2.f90
  src/math/bcknd/xsmm/ax_helm_xsmm.F90
  src/math/bcknd/xsmm/opr_xsmm.F90
  src/math/operators.f90
  src/mesh/mesh.f90
  src/qoi/drag_torque.f90
  src/scalar/scalar_pnpn.f90
  src/sem/cpr.f90
  src/simulation.f90
  src/simulation_components/probes.F90
Labels: enhancement, compilers, Fujitsu

#1279 Feature/zone_ic
  doc/pages/user-guide/case-file.md
  src/.depends
  src/fluid/flow_ic.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/math.f90
  src/scalar/scalar_ic.f90
Labels: enhancement

#1265 Add Sigma and Smagorinsky model, fix the Vreman model.
  src/.depends
  src/Makefile.am
  src/les/bcknd/cpu/sigma_cpu.f90
  src/les/bcknd/cpu/smagorinsky_cpu.f90
  src/les/bcknd/cpu/vreman_cpu.f90
  src/les/les_model_fctry.f90
  src/les/sigma.f90
  src/les/smagorinsky.f90
Labels: enhancement

#1291 Update of flinter
  flinter_rc.yml
Labels: CI

#1290 Use standard language constructs to guide vectorisation
  src/common/bcknd/cpu/rhs_maker_cpu.f90
  src/fluid/bcknd/cpu/pnpn_res_cpu.f90
Labels: compilers, performance

#1292 Avoid F77 style arguments
  src/sem/interpolation.f90
Labels: bug, enhancement

#1295 "Rework CI for linting and use new linting in main CI"
  .github/workflows/develop.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
Labels: CI
