Repository ExtremeFLOW/neko, pull requests merged in 2024-06, with the labels that each got.

#1298 Complete rework of the CI pipelines
  .github/actions/setup_json-fortran/action.yml
  .github/actions/setup_json-fortran/readme.md
  .github/actions/setup_pfunit/action.yml
  .github/actions/setup_pfunit/readme.md
  .github/workflows/check_gnu.yml
  .github/workflows/check_intel.yml
  .github/workflows/check_lint.yml
  .github/workflows/check_nvidia.yml
  .github/workflows/check_reframe.yml
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: CI

#1303 Fix CI - Now on correct repository
  .github/actions/setup_json-fortran/action.yml
  .github/workflows/check_gnu.yml
Labels: bug, CI

#1301 Update error handling of actions
  .github/actions/setup_json-fortran/action.yml
  .github/actions/setup_json-fortran/readme.md
  .github/actions/setup_pfunit/action.yml
  .github/actions/setup_pfunit/readme.md
  .github/workflows/check_gnu.yml
  .github/workflows/check_lint.yml
  .github/workflows/check_reframe.yml
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: CI

#1307 Remove extra if statement cased by bad merge
  .github/workflows/check_gnu.yml
Labels: bug

#1300 Add list of fields in statistics doc
  doc/pages/user-guide/statistics-guide.md
Labels: documentation

#1269 Remove reduntant constructor in fluid
  src/common/material_properties.f90
  src/fluid/fluid_scheme.f90
Labels: refactor

#1309 Fix/main-ci
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: bug, CI

#1308 Initial wall model implementation
  src/.depends
  src/Makefile.am
  src/common/utils.f90
  src/wall_models/rough_log_law.f90
  src/wall_models/spalding.f90
  src/wall_models/wall_model.f90
  src/wall_models/wall_model_fctry.f90
Labels: enhancement

#1315 Automatic detection of intel compiler version
  .github/workflows/check_intel.yml
Labels: compilers, CI

#1314 Update the hemi example to explciit bc setting
  examples/hemi/hemi.case
  examples/hemi/hemi.nmsh
  examples/hemi/hemi.re2
  examples/hemi/run.sh
Labels: case

#1320 OS Version updates
  .github/workflows/check_depend.yml
  .github/workflows/check_gnu.yml
  .github/workflows/check_intel.yml
  .github/workflows/check_nvidia.yml
  .github/workflows/check_reframe.yml
Labels: CI

#1316 Add stress and wall model bcs, set flux to array in neumman
  examples/scalar_mms/plot.py
  src/.depends
  src/Makefile.am
  src/bc/neumann.f90
  src/bc/shear_stress.f90
  src/bc/wall_model_bc.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1325 Add LES for the scalar
  doc/pages/user-guide/case-file.md
  src/.depends
  src/scalar/bcknd/cpu/scalar_residual_cpu.f90
  src/scalar/bcknd/device/scalar_residual_device.F90
  src/scalar/bcknd/sx/scalar_residual_sx.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_residual.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement
