Repository ExtremeFLOW/neko, pull requests merged in 2024-10, with the labels that each got.

#1489 Add logging levels and improve error handling
  doc/pages/appendices.md
  src/common/json_utils.f90
  src/common/log.f90
  src/common/utils.f90
  src/neko.f90
Labels: documentation, enhancement

#1522 fix fluid source terms
  src/fluid/fluid_scheme.f90
Labels: bug

#1527 Update ROCm installation process
  .github/workflows/check_gnu.yml
Labels: AMD

#1528 Fix scalar scheme message for material properties
  src/scalar/scalar_scheme.f90
Labels: bug

#1529 Fix invalid opencl events calling sequence
  src/device/device.F90
  src/device/opencl_intf.F90
Labels: bug, GPU, OpenCL

#1532 cheby: fix parameter sequence
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/bcknd/device/cheby_device.F90
Labels: bug

#1494 Fluid statistics as simcomp and 1D/2D stats
  contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90
  doc/pages/user-guide/simcomps.md
  doc/pages/user-guide/statistics-guide.md
  examples/turb_channel/turb_channel.case
  src/.depends
  src/Makefile.am
  src/case.f90
  src/field/mean_field.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_stats.f90
  src/io/fld_file.f90
  src/io/fluid_stats_output.f90
  src/sem/map_1d.f90
  src/simulation.f90
  src/simulation_components/fluid_stats_simcomp.f90
  src/simulation_components/simulation_component_fctry.f90
Labels: enhancement

#1534 Fix compilation issues with Fujitsu Fortran v4.11.2
  src/common/gradient_jump_penalty.f90
Labels: bug, compilers, Fujitsu

#1535 Fix json parsing in scalar scheme
  src/scalar/scalar_scheme.f90
Labels: bug

#1366 Initial condition from fld or chkp
  doc/pages/user-guide/case-file.md
  src/.depends
  src/case.f90
  src/common/global_interpolation.F90
  src/common/utils.f90
  src/fluid/flow_ic.f90
  src/io/fld_file_data.f90
  src/scalar/scalar_ic.f90
  src/simulation_components/probes.F90
Labels: documentation, enhancement

#1538 Refactor C to this in case
  src/case.f90
Labels: refactor

#1543 Brinkman forcing bug on gpu.
  src/.depends
  src/source_terms/brinkman/filters.f90
Labels: bug

#1545 Fix boussinesq json parsing
  src/source_terms/boussinesq_source_term.f90
Labels: bug

#1544 Move mass matrix multiply to source handler
  src/.depends
  src/fluid/fluid_pnpn.f90
  src/scalar/scalar_pnpn.f90
  src/source_terms/source_term_handler.f90
Labels: enhancement

#1552 A mesh checker utility
  configure.ac
  contrib/Makefile.am
  contrib/mesh_checker/Makefile.am
  contrib/mesh_checker/mesh_checker.f90
Labels: enhancement

#1553 Add missing restart options
  doc/pages/user-guide/case-file.md
Labels: documentation

#1561 Remove deprecated compiler
  .github/workflows/check_intel.yml
Labels: CI

#1567 glmin/max tolerant to n=0
  src/math/math.f90
Labels: enhancement

#1560 Add axis-aligned bcs for shear stress and wall modelling
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/simcomps.md
  src/.depends
  src/bc/bc.f90
  src/bc/neumann.f90
  src/bc/shear_stress.f90
  src/bc/wall_model_bc.f90
  src/common/json_utils.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/wall_models/rough_log_law.f90
  src/wall_models/wall_model.f90
  src/wall_models/wall_model_fctry.f90
Labels: bug, enhancement

#1566 Fix dangling pointers from Case and scratch init
  src/case.f90
  src/field/scratch_registry.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/io/fluid_output.f90
  src/neko.f90
Labels: bug, compilers
