Repository ExtremeFLOW/neko, pull requests merged in 2025-01, with the labels that each got.

#1655 Fix Poisson example
  examples/poisson/ax_poisson.f90
  examples/poisson/driver.f90
  src/.depends
  src/neko.f90
Labels: bug, enhancement

#1654 Move job info to an own subroutine
  src/neko.f90
Labels: enhancement

#1656 Fix segfault in mesh redistribution
  src/comm/redist.f90
  src/mesh/mesh.f90
Labels: bug

#1659 Add missing features in prepart
  contrib/prepart/prepart.f90
Labels: bug

#1600 A little change on LES models
  src/.depends
  src/les/bcknd/cpu/dynamic_smagorinsky_cpu.f90
  src/les/bcknd/cpu/sigma_cpu.f90
  src/les/bcknd/cpu/smagorinsky_cpu.f90
  src/les/bcknd/cpu/vreman_cpu.f90
  src/les/bcknd/device/sigma_device.f90
  src/les/bcknd/device/vreman_device.f90
  src/les/les_model.f90
  src/simulation_components/les_simcomp.f90
Labels: enhancement

#1660 Change nmsh to use glb el index, allowing for parallel writes
  contrib/genmeshbox/genmeshbox.f90
  contrib/prepart/prepart.f90
  src/case.f90
  src/comm/redist.f90
  src/io/nmsh_file.f90
  src/io/re2_file.f90
  src/io/rea_file.f90
  src/mesh/mesh.f90
  tests/unit/dofmap/dofmap_parallel.pf
  tests/unit/field/field_parallel.pf
  tests/unit/gather_scatter/gather_scatter_parallel.pf
  tests/unit/mean_field/mean_field_parallel.pf
  tests/unit/mean_sqr_field/mean_sqr_field_parallel.pf
  tests/unit/mesh/mesh_parallel.pf
  tests/unit/point_interpolation/point_interpolation_parallel.pf
  tests/unit/scratch_registry/test_scratch_registry.pf
Labels: enhancement

#1664 Fix curve offset
  src/io/nmsh_file.f90
Labels: bug

#1665 Fix issues with the roctx m4 macro
  m4/ax_roctx.m4
Labels: bug

#1671 Remove unnecessary parameters from fluid_scheme class
  src/fluid/fluid_scheme.f90
Labels: enhancement

#1677 Remove "type: binary" from .nek5000
  src/io/fld_file.f90
Labels: enhancement

#1678 Remove redundant sweep over all grid points for nab.eq.3
  src/common/bcknd/cpu/rhs_maker_cpu.f90
Labels: Fujitsu, performance

#1680 Fix HIP warnings
  src/krylov/bcknd/device/hip/fusedcg_cpld_aux.hip
Labels: GPU, AMD

#1681 Optimise the device computation of the eddy viscosity field
  src/les/bcknd/device/cuda/dynamic_smagorinsky_nut.cu
  src/les/bcknd/device/cuda/dynamic_smagorinsky_nut_kernel.h
  src/les/bcknd/device/cuda/sigma_nut_kernel.h
  src/les/bcknd/device/cuda/smagorinsky_nut_kernel.h
  src/les/bcknd/device/cuda/vreman_nut_kernel.h
  src/les/bcknd/device/device_dynamic_smagorinsky_nut.F90
  src/les/bcknd/device/dynamic_smagorinsky_device.f90
  src/les/bcknd/device/hip/dynamic_smagorinsky_nut.hip
  src/les/bcknd/device/hip/dynamic_smagorinsky_nut_kernel.h
  src/les/bcknd/device/hip/sigma_nut_kernel.h
  src/les/bcknd/device/hip/smagorinsky_nut_kernel.h
  src/les/bcknd/device/hip/vreman_nut_kernel.h
Labels: enhancement, GPU, NVIDIA, AMD

#1404 Fix invalid loop bounds for triangle elements
  src/mesh/tri.f90
Labels: bug

#1065 Fix formatter action
  .github/workflows/check_format.yml
  .github/workflows/develop.yml
  .github/workflows/extra/requirements-formatting.txt
  .github/workflows/formatter.yml
  CONTRIBUTING.md
  doc/pages/developer-guide/code-style.md
  doc/pages/developer-guide/contributing.md
Labels: CI
