Repository ExtremeFLOW/neko, pull requests merged in 2025-02, with the labels that each got.

#1684 Stop indenting case lines in select statements
  .github/workflows/check_format.yml
  doc/pages/developer-guide/code-style.md
Labels: bug, CI

#1666 Compressible solver
  configure.ac
  doc/pages/developer-guide/important_types.md
  examples/euler_1d_sod/README.md
  examples/euler_1d_sod/clean.sh
  examples/euler_1d_sod/run.sh
  examples/euler_1d_sod/sod.case
  examples/euler_1d_sod/sod.f90
  examples/euler_2d_smooth/README.md
  examples/euler_2d_smooth/clean.sh
  examples/euler_2d_smooth/euler_2d_smooth.case
  examples/euler_2d_smooth/euler_2d_smooth.f90
  examples/euler_2d_smooth/run.sh
  examples/euler_tgv/README.md
  examples/euler_tgv/clean.sh
  examples/euler_tgv/euler_tgv.case
  examples/euler_tgv/euler_tgv.f90
  examples/euler_tgv/run.sh
  src/.depends
  src/Makefile.am
  src/bc/field_dirichlet.f90
  src/bc/field_dirichlet_vector.f90
  src/case.f90
  src/common/user_intf.f90
  src/fluid/bcknd/cpu/euler_res_cpu.f90
  src/fluid/bcknd/device/cuda/euler_res.cu
  src/fluid/bcknd/device/cuda/euler_res_kernel.h
  src/fluid/bcknd/device/euler_res_device.F90
  src/fluid/bcknd/device/hip/euler_res.hip
  src/fluid/bcknd/device/hip/euler_res_kernel.h
  src/fluid/bcknd/sx/euler_res_sx.f90
  src/fluid/euler_res.f90
  src/fluid/euler_res_fctry.f90
  src/fluid/flow_ic.f90
  src/fluid/fluid_base_fctry.f90
  src/fluid/fluid_fctry.f90
  src/fluid/fluid_plan1.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme.f90
  src/fluid/fluid_scheme_base.f90
  src/fluid/fluid_scheme_compressible.f90
  src/fluid/fluid_scheme_compressible_euler.f90
  src/fluid/fluid_scheme_incompressible.f90
  src/fluid/fluid_source_term.f90
  src/io/fluid_output.f90
  src/simulation.f90
  src/simulation_components/les_simcomp.f90
  src/time_schemes/runge_kutta_scheme.f90
  tests/unit/Makefile.am
  tests/unit/runge_kutta_scheme/Makefile.in
  tests/unit/runge_kutta_scheme/test_runge_kutta_scheme.pf
Labels: enhancement, NVIDIA, AMD

#1679 Remove lid2d.f90
  Makefile.am
  examples/lid/lid2d.f90
Labels: case

#1691 Lift freeze fluid flag to top level
  src/fluid/fluid_scheme_base.f90
  src/fluid/fluid_scheme_incompressible.f90
Labels: refactor

#1697 Fix small typo in the fluid log
  src/fluid/fluid_pnpn.f90
Labels: bug, documentation

#1700 Fix handling of optional args in bc list apply
  src/bc/bc_list.f90
Labels: bug

#1701 Fix invalid interface (implicit types)
  src/math/bcknd/device/ax_helm_device.F90
Labels: bug, GPU, NVIDIA, AMD, OpenCL

#1702 Fix various issues with CCE 18.x
  src/adt/htable.f90
  src/case.f90
  src/io/fluid_output.f90
Labels: compilers, Cray

#1704 Atomic min max GS operator
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/cuda/gs_kernels.h
  src/gs/bcknd/device/hip/gs.hip
  src/gs/bcknd/device/hip/gs_kernels.h
  tests/bench/gs/driver.f90
  tests/unit/gather_scatter/gather_scatter_parallel.pf
Labels: NVIDIA, AMD, performance

#1713 Remove redunant docs and update user file docs
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/user-file.md
Labels: documentation

#1711 Update ax_helm_full_device.F90
  src/math/bcknd/device/ax_helm_full_device.F90
Labels: bug

#1714 Add NCCL as an option for collective communication
  m4/ax_nccl.m4
  src/Makefile.am
  src/comm/comm.F90.in
  src/comm/comm_nccl.c
  src/comm/comm_nccl.h
  src/krylov/bcknd/device/cuda/fusedcg_aux.cu
  src/krylov/bcknd/device/cuda/gmres_aux.cu
  src/math/bcknd/device/cuda/device_nccl_op.h
  src/math/bcknd/device/cuda/device_nccl_reduce.c
  src/math/bcknd/device/cuda/device_nccl_reduce.h
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/opr_cfl.cu
Labels: GPU, NVIDIA, performance

#1716 updated compile instructions for json
  README.md
Labels: documentation

#1719 Add option to write a field with zone ids to mesh_checker
  contrib/mesh_checker/mesh_checker.f90
  doc/pages/user-guide/case-file.md
Labels: enhancement

#1721 Add NCCL comm backend for gather-scatter
  src/.depends
  src/Makefile.am
  src/gs/bcknd/device/device_nccl.c
  src/gs/bcknd/device/gs_device_nccl.F90
  src/gs/gather_scatter.f90
  src/gs/gs_comm.f90
Labels: GPU, NVIDIA, performance

#1722 Add support RCCL in collective and gs comm.
  m4/ax_rccl.m4
  src/Makefile.am
  src/comm/comm.F90.in
  src/comm/comm_nccl.c
  src/comm/comm_nccl.h
  src/gs/bcknd/device/device_nccl.c
  src/krylov/bcknd/device/cuda/fusedcg_aux.cu
  src/krylov/bcknd/device/cuda/gmres_aux.cu
  src/krylov/bcknd/device/hip/fusedcg_aux.hip
  src/krylov/bcknd/device/hip/gmres_aux.hip
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/opr_cfl.cu
  src/math/bcknd/device/device_nccl_op.h
  src/math/bcknd/device/device_nccl_reduce.c
  src/math/bcknd/device/device_nccl_reduce.h
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/opr_cfl.hip
Labels: GPU, AMD, performance

#1728 NVSHMEM comm. backend for gather-scatter
  Makefile.am
  configure.ac
  m4/ax_nvshmem.m4
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/comm/bcknd/device/cuda/comm_nvshmem.cu
  src/comm/comm.F90.in
  src/gs/bcknd/device/cuda/gs_nvshmem.cu
  src/gs/bcknd/device/cuda/gs_nvshmem_kernels.h
  src/gs/bcknd/device/gs_device_shmem.F90
  src/gs/gather_scatter.f90
  src/gs/gs_comm.f90
Labels: GPU, NVIDIA, performance

#1495 Adds documentation for LES models and governing equations
  doc/pages/appendices/governing-equations.md
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/simcomps.md
  tests/reframe/.gitignore
Labels: documentation

#1731 Add NVSHMEM collectives (reductions)
  src/krylov/bcknd/device/cuda/fusedcg_aux.cu
  src/krylov/bcknd/device/cuda/fusedcg_cpld_aux.cu
  src/krylov/bcknd/device/cuda/gmres_aux.cu
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/cuda/opr_cfl.cu
Labels: GPU, NVIDIA, performance

#1734 Fix documentation and behavior for 1D stats
  doc/pages/user-guide/statistics-guide.md
  src/simulation_components/fluid_stats_simcomp.f90
Labels: bug

#1737 Update runners to ubuntu 24.04 before EOL of 20.04
  .github/workflows/check_depend.yml
  .github/workflows/check_format.yml
  .github/workflows/check_gnu.yml
  .github/workflows/check_intel.yml
  .github/workflows/check_lint.yml
  .github/workflows/check_nvidia.yml
  .github/workflows/check_reframe.yml
Labels: CI
