Repository ExtremeFLOW/neko, pull requests merged in 2025-04, with the labels that each got.

#1811 Override CMake policy for JSON-Fortran compatibility with Intel compiler
  .github/actions/setup_json-fortran/action.yml
Labels: CI

#1813 Fix poisson example
  examples/poisson/ax_poisson.f90
Labels: bug

#1793 Add type injection for LES models and source terms
  makeneko.in
  src/.depends
  src/les/les_model.f90
  src/les/les_model_fctry.f90
  src/neko.f90
  src/simulation_components/les_simcomp.f90
  src/source_terms/source_term.f90
  src/source_terms/source_term_fctry.f90
Labels: enhancement

#1816 Enhance option parsing for macOS compatibility
  contrib/lint_format/format.sh
  contrib/lint_format/lint.sh
Labels: bug

#1815 Fix docstrings
  src/common/time_state.f90
Labels: documentation

#1818 Add type injection to simcomp factories
  src/simulation_components/simulation_component.f90
  src/simulation_components/simulation_component_fctry.f90
Labels: enhancement

#1822 Fix/tstep
  src/simulation.f90
Labels: bug

#1829 Fix repository to use noble instead of focal and clean up debug prints
  .github/workflows/check_gnu.yml
Labels: CI

#1828 Make non-convergence warning only print once
  src/.depends
  src/fluid/fluid_aux.f90
Labels: enhancement

#1833 Rework sync in fusedcoupledcg
  src/krylov/bcknd/device/fusedcg_cpld_device.F90
Labels: GPU, NVIDIA, AMD

#1832 Update for nvhpc 25.3
  .github/workflows/check_nvidia.yml
Labels: CI

#1838 Fixed device memory allocation
  src/.depends
  src/bc/usr_inflow.f90
  src/bc/usr_scalar.f90
  src/math/schwarz.f90
Labels: bug, compilers, GPU, NVIDIA, AMD, NAG, OpenCL

#1842 Don't allocate unecessary zero sized arrays
  src/common/projection.f90
Labels: bug, enhancement

#1846 add start_time for probes
  doc/pages/user-guide/simcomps.md
  src/simulation_components/probes.F90
Labels: enhancement

#1848 Fix invalid index in coef (opencl)
  src/sem/bcknd/device/opencl/coef_kernel.cl
Labels: bug, GPU, OpenCL

#1825 Fix Coriolis term bug
  src/.depends
  src/source_terms/bcknd/cpu/coriolis_source_term_cpu.f90
  src/source_terms/coriolis_source_term.f90
Labels: bug

#1855 correct intent of field_sub3
  src/math/field_math.f90
Labels: bug

#1858 Fix gigabug with Neumann on the device
  src/bc/neumann.f90
Labels: bug, GPU

#1857 Add masked_scatter_copy and masked_gather_copy for OpenCL
  src/math/bcknd/device/cuda/cuda_math.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/bcknd/device/opencl/opencl_math.f90
  src/math/math.f90
Labels: enhancement, OpenCL

#1840 Update CITATION.cff
  CITATION.cff
Labels: documentation

#1845 Type injection improvements
  makeneko.in
  src/.depends
  src/common/user_intf.f90
  src/common/utils.f90
  src/les/les_model.f90
  src/les/les_model_fctry.f90
  src/neko.f90
  src/simulation_components/simulation_component_fctry.f90
  src/source_terms/source_term_fctry.f90
Labels: enhancement

#1852 Add build system and folder structure docs for the device
  doc/pages/developer-guide/contributing.md
Labels: documentation

#1856 Add a poor mans' device implementation for Coriolis
  src/.depends
  src/Makefile.am
  src/source_terms/bcknd/device/coriolis_source_term_device.f90
  src/source_terms/coriolis_source_term.f90
Labels: enhancement

#1860 Fix bounds in masked gather/scatter copies
  src/math/bcknd/device/cuda/cuda_math.f90
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/hip_math.f90
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/bcknd/device/opencl/opencl_math.f90
  src/math/field_math.f90
  src/math/math.f90
Labels: bug

#1862 Fix invalid arg for pnpn_res OpenCL
  src/fluid/bcknd/device/pnpn_res_device.F90
Labels: bug, GPU, OpenCL

#1863 Fix JIT error for facet normal and neumann kernel (OpenCL)
  src/bc/bcknd/device/opencl/facet_normal_kernel.cl
  src/bc/bcknd/device/opencl/neumann_kernel.cl
Labels: bug, GPU, OpenCL

#1861 Add missing vcross kernel for OpenCL
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/bcknd/device/opencl/opencl_math.f90
Labels: GPU, OpenCL

#1864 Harmonise all tnsr3d device kernels
  src/math/bcknd/device/opencl/tensor.c
  src/math/bcknd/device/opencl/tensor_kernel.cl
Labels: enhancement, GPU, OpenCL

#1866 Fix missing queue argument, and optimise extrude kernel
  src/math/bcknd/device/opencl/schwarz.c
  src/math/bcknd/device/opencl/schwarz_kernel.cl
Labels: bug, GPU, OpenCL

#1868 Check bounding box and right-handedness in the mesh
  src/mesh/mesh.f90
  tests/unit/math/math_parallel.pf
  tests/unit/mesh/mesh_parallel.pf
Labels: enhancement
