Repository ExtremeFLOW/neko, pull requests merged in 2025-07, with the labels that each got.

#1908 Fix material property hacks in fluid, force_torque and wall models
  src/.depends
  src/bc/wall_model_bc.f90
  src/field/scratch_registry.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_pnpn_bc_fctry.f90
  src/fluid/fluid_scheme_incompressible.f90
  src/fluid/fluid_volflow.f90
  src/math/bcknd/device/cuda/cuda_math.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/hip_math.f90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/field_math.f90
  src/neko.f90
  src/qoi/drag_torque.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
  src/simulation_components/force_torque.f90
  src/wall_models/bcknd/cpu/rough_log_law_cpu.f90
  src/wall_models/bcknd/cpu/spalding_cpu.f90
  src/wall_models/bcknd/device/cuda/rough_log_law.cu
  src/wall_models/bcknd/device/cuda/rough_log_law_kernel.h
  src/wall_models/bcknd/device/cuda/spalding.cu
  src/wall_models/bcknd/device/cuda/spalding_kernel.h
  src/wall_models/bcknd/device/hip/rough_log_law.hip
  src/wall_models/bcknd/device/hip/rough_log_law_kernel.h
  src/wall_models/bcknd/device/hip/spalding.hip
  src/wall_models/bcknd/device/hip/spalding_kernel.h
  src/wall_models/bcknd/device/rough_log_law_device.F90
  src/wall_models/bcknd/device/spalding_device.F90
  src/wall_models/rough_log_law.f90
  src/wall_models/spalding.f90
  src/wall_models/wall_model.f90
  src/wall_models/wall_model_fctry.f90
Labels: enhancement

#1998 Make sure mu_tot is filled, fixes #1997
  src/fluid/fluid_scheme_incompressible.f90
Labels: bug

#2001 Add the possibility to compile .cu and .hip files with makeneko
  makeneko.in
Labels: enhancement, GPU, NVIDIA, AMD

#2002 Update docs with info on makeneko's cuda/hip support
  doc/pages/user-guide/extension.md
  doc/pages/user-guide/user-file.md
Labels: documentation

#1996 Merge old cylinder test into the pytest suite
  .github/workflows/check_gnu.yml
  Makefile.am
  tests/integration/conftest.py
  tests/integration/testlib.py
  tests/integration/tests/test_cylinder/.gitignore
  tests/integration/tests/test_cylinder/cylinder_part1.case
  tests/integration/tests/test_cylinder/reflog1_dp.csv
  tests/integration/tests/test_cylinder/reflog1_sp.csv
  tests/integration/tests/test_cylinder/reflog2_dp.csv
  tests/integration/tests/test_cylinder/reflog2_sp.csv
  tests/integration/tests/test_cylinder/test_cylinder.py
  tests/integration/tests/test_demo/test_suite.py
  tests/regression/README.md
  tests/regression/cylinder/.gitignore
  tests/regression/cylinder/cylinder_part2.case
  tests/regression/cylinder/ref1_dp.log
  tests/regression/cylinder/ref1_sp.log
  tests/regression/cylinder/ref2_dp.log
  tests/regression/cylinder/ref2_sp.log
  tests/regression/cylinder/small_test_cyl.nmsh
  tests/regression/cylinder/test.sh
  tests/regression/cylinder/test_easy.sh
Labels: CI

#2006 Update linter to check for missing spaces after `only`
  flinter_rc.yml
  src/source_terms/brinkman_source_term.f90
Labels: CI

#2007 Remove implicit save in bcs
  src/bc/blasius.f90
  src/bc/dirichlet.f90
  src/bc/dong_outflow.f90
  src/bc/field_dirichlet.f90
  src/bc/field_dirichlet_vector.f90
  src/bc/inflow.f90
  src/bc/neumann.f90
  src/bc/shear_stress.f90
  src/bc/symmetry.f90
  src/bc/usr_inflow.f90
  src/bc/usr_scalar.f90
  src/bc/wall_model_bc.f90
  src/bc/zero_dirichlet.f90
Labels: bug

#2008 Fix programming examples, add their compilation to CI
  examples/programming/custom_types.f90
  examples/programming/user_file_template.f90
  tests/integration/tests/test_examples/test_examples.py
Labels: case, CI

#2017 Fix bcs in HSMG that were not quite ok
  src/krylov/pc_hsmg.f90
Labels: bug

#2019 Add missing memset in field init, make it consistent with host
  .github/workflows/check_gnu.yml
  src/field/field.f90
Labels: bug, GPU
