Repository ExtremeFLOW/neko, pull requests merged in 2025-06, with the labels that each got.

#1915 Fix void pointer increment and race in gs_scatter
  src/gs/bcknd/device/cuda/gs_kernels.h
  src/gs/bcknd/device/device_mpi.c
  src/gs/bcknd/device/hip/gs_kernels.h
Labels: bug

#1611 format change of log file for easier parsing and reducing the number of lines printed
  doc/pages/appendices.md
  src/.depends
  src/common/log.f90
  src/common/projection.f90
  src/common/time_state.f90
  src/fluid/fluid_aux.f90
  src/simulation.f90
  src/wall_models/bcknd/cpu/spalding_cpu.f90
  src/wall_models/wall_model.f90
  tests/regression/cylinder/ref1_dp.log
  tests/regression/cylinder/ref1_sp.log
  tests/regression/cylinder/ref2_dp.log
  tests/regression/cylinder/ref2_sp.log
  tests/regression/cylinder/test.sh
  tests/regression/cylinder/test_easy.sh
Labels: enhancement

#1914 Add possibility to add aliases to field_register_t
  configure.ac
  src/.depends
  src/field/field_registry.f90
  tests/unit/Makefile.am
  tests/unit/field_registry/Makefile.in
  tests/unit/field_registry/test_field_registry.pf
Labels: enhancement, refactor

#1929 Fix/bc
  src/bc/bc.f90
Labels: bug

#1928 Some more fixes for gs and avoid accidently deallocating things too early
  src/gs/bcknd/device/gs_device.F90
  src/gs/bcknd/device/gs_device_mpi.F90
  src/gs/gather_scatter.f90
  src/sem/space.f90
Labels: bug

#1934 Example/euler
  examples/euler_1d_sod/run.sh
  examples/euler_2d_smooth/run.sh
  examples/euler_tgv/run.sh
Labels: bug, case

#1795 Multiple scalars
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/user-file.md
  examples/advecting_cone/advecting_cone.f90
  examples/rayleigh_benard/rayleigh.f90
  examples/rayleigh_benard_cylinder/rayleigh.f90
  examples/scalar_mms/scalar_mms.f90
  src/.depends
  src/Makefile.am
  src/bc/usr_scalar.f90
  src/case.f90
  src/common/user_intf.f90
  src/fluid/fluid_source_term.f90
  src/io/fluid_output.f90
  src/scalar/scalar_ic.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_pnpn_bc_fctry.f90
  src/scalar/scalar_scheme.f90
  src/scalar/scalar_source_term.f90
  src/scalar/scalar_user_source_term.f90
  src/scalar/scalars.f90
  src/simulation.f90
  src/source_terms/source_term_handler.f90
  tests/reframe/src/rayleigh.f90
Labels: enhancement

#1880 Add possibility to install with pixi
  .gitignore
  doc/pages/user-guide/installation.md
  pixi.toml
Labels: enhancement

#1933 Add device memset interfaces
  src/device/cuda_intf.F90
  src/device/device.F90
  src/device/hip_intf.F90
  src/device/opencl_intf.F90
Labels: GPU, NVIDIA, AMD, OpenCL

#1942 Fix broken hemi example
  examples/hemi/hemi.case
Labels: bug

#1945 Refactor file_t constructor to a normal procedure
  contrib/adios2_to_nek5000/adios2_to_nek5000.f90
  contrib/average_field_in_space/average_field_in_space.f90
  contrib/average_fields_in_time/average_fields_in_time.f90
  contrib/calc_lift_from_field/calc_lift_from_field.f90
  contrib/genmeshbox/genmeshbox.f90
  contrib/map_to_equidistant_1d/map_to_equidistant_1d.f90
  contrib/mesh_checker/mesh_checker.f90
  contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90
  contrib/prepart/prepart.f90
  contrib/psnr/psnr.f90
  contrib/rea2nbin/rea2nbin.f90
  examples/poisson/driver.f90
  src/bc/bc.f90
  src/case.f90
  src/common/runtime_statistics.f90
  src/fluid/flow_ic.f90
  src/fluid/fluid_pnpn.f90
  src/io/file.f90
  src/io/output.f90
  src/scalar/scalar_ic.f90
  src/simulation.f90
  src/simulation_components/probes.F90
  src/source_terms/brinkman_source_term.f90
  src/wall_models/wall_model.f90
  tests/bench/ax/driver.f90
  tests/bench/gs/driver.f90
  tests/bench/nekbone/driver.f90
Labels: refactor

#1952 Fix checkpoint output constructor
  src/case.f90
  src/io/chkp_output.f90
Labels: refactor

#1954 Fixed undefined and dangling pointers
  src/common/user_access_singleton.f90
  src/io/output.f90
  src/math/fdm.f90
  src/simulation_components/curl_simcomp.f90
  src/simulation_components/derivative_simcomp.f90
  src/simulation_components/divergence_simcomp.f90
  src/simulation_components/field_writer.f90
  src/simulation_components/fluid_stats_simcomp.f90
  src/simulation_components/force_torque.f90
  src/simulation_components/gradient_simcomp.f90
  src/simulation_components/lambda2.f90
  src/simulation_components/les_simcomp.f90
  src/simulation_components/probes.F90
  src/simulation_components/simulation_component.f90
  src/simulation_components/spectral_error.f90
  src/simulation_components/weak_gradient_simcomp.f90
Labels: bug, NAG

#1956 Add normed difference operator and optional tolerance for comparisons
  src/math/bcknd/device/cuda/cuda_math.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/hip_math.f90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
  src/math/bcknd/device/opencl/opencl_math.f90
  src/math/field_math.f90
  src/math/math.f90
Labels: GPU, NVIDIA, AMD, OpenCL

#1955 Fix warnings spotted by gcc 15
  src/field/field_list.f90
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/wall_models/bcknd/cpu/spalding_cpu.f90
  src/wall_models/wall_model.f90
Labels: bug, compilers

#1957 Add a device_memset before any gs operations (for extra safety)
  src/.depends
  src/gs/bcknd/device/gs_device.F90
  src/gs/bcknd/device/gs_device_mpi.F90
Labels: GPU, NVIDIA, AMD, OpenCL

#1958 Various OpenCL fixes, pnpn runs again
  src/gs/bcknd/device/gs_device.F90
  src/gs/bcknd/device/opencl/gs.c
  src/gs/bcknd/device/opencl/gs_kernels.cl
  src/math/bcknd/device/opencl/ax_helm_kernel.cl
  src/math/bcknd/device/opencl/cdtp_kernel.cl
  src/math/bcknd/device/opencl/cfl_kernel.cl
  src/math/bcknd/device/opencl/conv1_kernel.cl
  src/math/bcknd/device/opencl/dudxyz_kernel.cl
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/opgrad_kernel.cl
  src/math/bcknd/device/opencl/opr_cdtp.c
  src/math/bcknd/device/opencl/opr_cfl.c
  src/math/bcknd/device/opencl/opr_conv1.c
Labels: bug, GPU, OpenCL

#1965 Fix invalid kernel arguments
  src/math/bcknd/device/opencl/math.c
Labels: bug, GPU, OpenCL

#1962 Cleanup gs, remove unused NULL stream code path
  src/gs/bcknd/device/cuda/gs.cu
  src/gs/bcknd/device/hip/gs.hip
Labels: GPU, NVIDIA, AMD

#1966 Fix error with pow in OpenCL kernels (+formatting)
  src/math/bcknd/device/opencl/math.c
  src/math/bcknd/device/opencl/math_kernel.cl
Labels: bug, GPU, OpenCL

#1967 Avoid host ptr being deallocated before memcpy is done
  src/gs/bcknd/device/gs_device_nccl.F90
  src/gs/bcknd/device/gs_device_shmem.F90
Labels: bug, GPU

#1972 Fix out of local mem. issues with OpenCL, verified on Mi250X
  src/math/bcknd/device/opencl/ax_helm_kernel.cl
  src/math/bcknd/device/opencl/cdtp_kernel.cl
  src/math/bcknd/device/opencl/cfl_kernel.cl
  src/math/bcknd/device/opencl/dudxyz_kernel.cl
  src/math/bcknd/device/opencl/opr_cdtp.c
  src/math/bcknd/device/opencl/opr_cfl.c
  src/math/bcknd/device/opencl/opr_dudxyz.c
Labels: bug, GPU, AMD, OpenCL

#1961 Add _ to ksp names
  doc/pages/user-guide/case-file.md
  src/krylov/krylov_fctry.f90
Labels: refactor

#1526 Integration tests with pytest
  .github/workflows/check_gnu.yml
  .github/workflows/check_intel.yml
  .github/workflows/check_nvidia.yml
  .github/workflows/develop.yml
  examples/lid/lid.f90
  tests/integration/.gitignore
  tests/integration/README.md
  tests/integration/conftest.py
  tests/integration/default_cpu_launcher.sh
  tests/integration/default_cuda_launcher.sh
  tests/integration/meshes/small_test_cyl.nmsh
  tests/integration/pytest.ini
  tests/integration/testlib.py
  tests/integration/tests/test_demo/test_suite.py
  tests/integration/tests/test_examples/test_examples.py
Labels: CI

#1976 Fix zero-sized array c_loc
  src/bc/facet_normal.f90
Labels: bug, GPU, NVIDIA, AMD, OpenCL

#1977 Time-step log, Field variable name field too short
  src/krylov/krylov.f90
  tests/regression/cylinder/test.sh
  tests/regression/cylinder/test_easy.sh
Labels: bug
