Repository ExtremeFLOW/neko, pull requests merged in 2025-03, with the labels that each got.

#1255 Various bugs related to BCs
  src/.depends
  src/bc/bc.f90
  src/bc/dong_outflow.f90
  src/bc/facet_normal.f90
  src/fluid/fluid_scheme_incompressible.f90
  tests/regression/cylinder/test.sh
Labels: bug, enhancement

#1742 Reduce costly sync with host for gather-scatter
  src/.depends
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme_incompressible.f90
Labels: performance

#1747 Remove std(?) violating c_ptr, and move event to device
  src/device/device.F90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme_incompressible.f90
Labels: bug

#1749 doc/Update governing-equations.md
  doc/pages/appendices/governing-equations.md
Labels: documentation

#1751 Update README.md
  README.md
Labels: documentation

#1752 GPU verison of phmg and tamg
  src/.depends
  src/krylov/pc_hsmg.f90
  src/krylov/precon_fctry.f90
  src/math/bcknd/device/cuda/cuda_math.f90
  src/math/bcknd/device/cuda/math.cu
  src/math/bcknd/device/cuda/math_kernel.h
  src/math/bcknd/device/device_math.F90
  src/math/bcknd/device/hip/hip_math.f90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
  src/multigrid/phmg.f90
  src/multigrid/tree_amg.f90
  src/multigrid/tree_amg_aggregate.f90
  src/multigrid/tree_amg_multigrid.f90
  src/multigrid/tree_amg_smoother.f90
  src/multigrid/tree_amg_utils.f90
Labels: enhancement, GPU

#1754 Fix missing only
  src/multigrid/phmg.f90
Labels: GPU

#1760 Add OpenCL backend for euler solver
  src/.depends_device
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/fluid/bcknd/device/euler_res_device.F90
  src/fluid/bcknd/device/opencl/euler_res.c
  src/fluid/bcknd/device/opencl/euler_res_kernel.cl
Labels: GPU, OpenCL

#1759 BCs for compressible solver
  examples/euler_2d_cylinder/README.md
  examples/euler_2d_cylinder/clean.sh
  examples/euler_2d_cylinder/cyl.nmsh
  examples/euler_2d_cylinder/euler_2d_cylinder.case
  examples/euler_2d_cylinder/euler_2d_cylinder.f90
  examples/euler_2d_forward_facing_step/README.md
  examples/euler_2d_forward_facing_step/clean.sh
  examples/euler_2d_forward_facing_step/step.case
  examples/euler_2d_forward_facing_step/step.f90
  examples/euler_2d_forward_facing_step/step.geo
  examples/euler_2d_forward_facing_step/step.nmsh
  examples/euler_tgv/euler_tgv.case
  src/.depends
  src/Makefile.am
  src/fluid/euler_bc_fctry.f90
  src/fluid/fluid_scheme_compressible_euler.f90
Labels: enhancement, compressible

#1768 Fix SEGV in vorticity simcomps due to missing event
  src/.depends
  src/math/bcknd/device/opr_device.F90
  src/math/operators.f90
  src/simulation_components/vorticity.f90
Labels: bug, GPU

#1767 Check for boundary_conditions entry when labled zones present
  src/fluid/fluid_pnpn.f90
  tests/reframe/src/minihemi.case.template
  tests/reframe/src/rayleigh.case.template
Labels: enhancement

#1772 Fix typo in pressure solver monitor
  src/fluid/fluid_pnpn.f90
Labels: bug

#1777 Typo README.md
  README.md
Labels: documentation

#1776 Fix missing weak_grad in simcomp factory
  doc/pages/user-guide/simcomps.md
  src/simulation_components/simulation_component.f90
  src/simulation_components/simulation_component_fctry.f90
Labels: bug

#1771 Some imporvements to scalar
  doc/pages/user-guide/case-file.md
  examples/scalar_mms/scalar_mms.case
  src/case.f90
  src/fluid/advection_fctry.f90
  src/fluid/fluid_pnpn.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
  tests/reframe/src/rayleigh.f90
Labels: bug, enhancement, refactor

#1762 See if we can simplify the ksp factory
  src/fluid/fluid_scheme_incompressible.f90
  src/krylov/bcknd/cpu/bicgstab.f90
  src/krylov/bcknd/cpu/cacg.f90
  src/krylov/bcknd/cpu/cg.f90
  src/krylov/bcknd/cpu/cg_coupled.f90
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/bcknd/cpu/gmres.f90
  src/krylov/bcknd/cpu/pipecg.f90
  src/krylov/bcknd/device/cg_device.f90
  src/krylov/bcknd/device/gmres_device.F90
  src/krylov/bcknd/sx/cg_sx.f90
  src/krylov/bcknd/sx/gmres_sx.f90
  src/krylov/bcknd/sx/pipecg_sx.f90
  src/krylov/krylov.f90
  src/krylov/krylov_fctry.f90
  src/krylov/pc_hsmg.f90
  src/multigrid/phmg.f90
  src/scalar/scalar_scheme.f90
  src/source_terms/brinkman/PDE_filter.f90
Labels: enhancement, refactor

#1788 Add name component to fluid and scalar schemes
  doc/pages/user-guide/case-file.md
  src/fluid/fluid_scheme_base.f90
  src/fluid/fluid_scheme_compressible.f90
  src/fluid/fluid_scheme_incompressible.f90
  src/scalar/scalar_scheme.f90
Labels: enhancement

#1787 Installation instructions for HDF5
  doc/pages/user-guide/installation.md
Labels: documentation

#1798 Fix formatting issue caused by link in documentation
  doc/pages/user-guide/user-file.md
Labels: documentation

#1791 Remove built-in zones from the code
  .gitignore
  contrib/mesh_checker/mesh_checker.f90
  contrib/prepart/prepart.f90
  src/comm/redist.f90
  src/io/nmsh_file.f90
  src/mesh/mesh.f90
Labels: refactor

#1799 Fix user simcomp setup bug
  examples/advecting_cone/run.sh
  examples/scalar_mms/run.sh
  src/common/user_intf.f90
  src/simulation_components/simcomp_executor.f90
Labels: bug
