Repository ExtremeFLOW/neko, pull requests merged in 2025-08, with the labels that each got.

#2035 Add Poisson example compilation test
  tests/integration/tests/test_examples/test_examples.py
Labels: CI

#2033 Update restart
  src/.depends
  src/common/time_state.f90
  src/io/chkp_file.f90
  src/simulation.f90
Labels: refactor

#2044 Fix missing symbols issues with nvhpc
  src/.depends
  src/source_terms/gradient_jump_penalty.f90
Labels: bug, compilers, NVIDIA

#2051 Fix use before allocated
  src/wall_models/bcknd/cpu/spalding_cpu.f90
Labels: bug

#2055 Multi scalars checkpoint hdf5
  doc/pages/user-guide/user-file.md
  src/.depends
  src/Makefile.am
  src/common/checkpoint.f90
  src/field/field_series_list.f90
  src/io/hdf5_file.F90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalars.f90
Labels: enhancement

#2061 Reorganize compressible kernels
  examples/euler_1d_sod/sod.case
  src/.depends
  src/.depends_device
  src/Makefile.am
  src/device/opencl/prgm_lib.F90
  src/device/opencl/prgm_lib.h
  src/fluid/bcknd/cpu/compressible_ops_cpu.f90
  src/fluid/bcknd/device/compressible_ops_device.F90
  src/fluid/bcknd/device/cuda/compressible_ops_compute_entropy.cu
  src/fluid/bcknd/device/cuda/compressible_ops_compute_max_wave_speed.cu
  src/fluid/bcknd/device/cuda/compressible_ops_kernel.h
  src/fluid/bcknd/device/cuda/opr_compute_entropy.cu
  src/fluid/bcknd/device/hip/compressible_ops_compute_entropy.hip
  src/fluid/bcknd/device/hip/compressible_ops_compute_max_wave_speed.hip
  src/fluid/bcknd/device/hip/compressible_ops_kernel.h
  src/fluid/bcknd/device/opencl/compressible_ops_compute_entropy.c
  src/fluid/bcknd/device/opencl/compressible_ops_compute_entropy_kernel.cl
  src/fluid/bcknd/device/opencl/compressible_ops_compute_max_wave_speed.c
  src/fluid/bcknd/device/opencl/compressible_ops_compute_max_wave_speed_kernel.cl
  src/fluid/fluid_scheme_compressible.f90
  src/fluid/fluid_scheme_compressible_euler.f90
  src/math/bcknd/cpu/opr_cpu.f90
  src/math/bcknd/device/opr_device.F90
  src/math/operators.f90
Labels: compressible

#2071 Fix invalid sp/dp assumption in API and pyneko code
  src/api/neko_api.f90
  src/python/pyneko/intf.py.in
Labels: bug, API

#2072 Workaround for compiling the API with NAG in single precision
  src/api/neko_api_user.f90
Labels: bug, compilers, NAG, API

#2074 Use math.f90 for cpu ops in vector
  src/.depends
  src/math/vector.f90
Labels: bug
