Repository ExtremeFLOW/neko, pull requests merged in 2025-05, with the labels that each got.

#1876 Disable right-handedness checker
  src/mesh/mesh.f90
Labels: bug

#1878 Fix missing distclean target
  tests/unit/bc/Makefile.in
  tests/unit/device/Makefile.in
  tests/unit/device_math/Makefile.in
  tests/unit/device_mathops/Makefile.in
  tests/unit/dofmap/Makefile.in
  tests/unit/fast3d/Makefile.in
  tests/unit/field/Makefile.in
  tests/unit/gather_scatter/Makefile.in
  tests/unit/hex/Makefile.in
  tests/unit/htable/Makefile.in
  tests/unit/jobctrl/Makefile.in
  tests/unit/krylov/Makefile.in
  tests/unit/math/Makefile.in
  tests/unit/mathops/Makefile.in
  tests/unit/matrix/Makefile.in
  tests/unit/mean_field/Makefile.in
  tests/unit/mean_sqr_field/Makefile.in
  tests/unit/mesh/Makefile.in
  tests/unit/octree/Makefile.in
  tests/unit/point/Makefile.in
  tests/unit/point_interpolation/Makefile.in
  tests/unit/quad/Makefile.in
  tests/unit/runge_kutta_scheme/Makefile.in
  tests/unit/scratch_registry/Makefile.in
  tests/unit/signal/Makefile.in
  tests/unit/space/Makefile.in
  tests/unit/stack/Makefile.in
  tests/unit/tet/Makefile.in
  tests/unit/time_based_controller/Makefile.in
  tests/unit/time_scheme/Makefile.in
  tests/unit/time_scheme_controller/Makefile.in
  tests/unit/tri/Makefile.in
  tests/unit/tuple/Makefile.in
  tests/unit/uset/Makefile.in
  tests/unit/vector/Makefile.in
Labels: bug

#1779 Redesign material_properties user routine and their handling in schemes
  doc/pages/user-guide/case-file.md
  doc/pages/user-guide/user-file.md
  examples/rayleigh_benard/rayleigh.f90
  examples/rayleigh_benard_cylinder/rayleigh.case
  examples/rayleigh_benard_cylinder/rayleigh.f90
  src/.depends
  src/case.f90
  src/common/user_intf.f90
  src/field/field_series.f90
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_pnpn_bc_fctry.f90
  src/fluid/fluid_scheme_base.f90
  src/fluid/fluid_scheme_compressible.f90
  src/fluid/fluid_scheme_compressible_euler.f90
  src/fluid/fluid_scheme_incompressible.f90
  src/math/ax_helm_full.f90
  src/scalar/scalar_pnpn.f90
  src/scalar/scalar_scheme.f90
  src/simulation.f90
  src/simulation_components/force_torque.f90
  src/simulation_components/les_simcomp.f90
  tests/reframe/src/rayleigh.f90
Labels: enhancement, refactor

#1851 Use a json subdict to extract and pass down (potential) precon params
  doc/pages/user-guide/case-file.md
  examples/2d_cylinder/2d_cylinder.case
  examples/TS_channel/TS_channel.case
  examples/advecting_cone/advecting_cone.case
  examples/cyl_boundary_layer/cyl_bl_basic.case
  examples/cyl_boundary_layer/cyl_bl_rot.case
  examples/cyl_boundary_layer/cyl_bl_user.case
  examples/cyl_boundary_layer/cyl_bl_user_test.case
  examples/cylinder/cylinder.case
  examples/hemi/hemi.case
  examples/immersed_bunny/immersed_bunny.case
  examples/immersed_zones/block.case
  examples/immersed_zones/block_sphere.case
  examples/immersed_zones/cylinder.case
  examples/immersed_zones/sphere.case
  examples/lid/lid.case
  examples/lid/lid2d.case
  examples/rayleigh_benard/rayleigh.case
  examples/rayleigh_benard_cylinder/rayleigh.case
  examples/scalar_mms/scalar_mms.case
  examples/tgv/tgv.case
  examples/turb_channel/turb_channel.case
  examples/turb_pipe/turb_pipe.case
  src/.depends
  src/fluid/fluid_pnpn.f90
  src/fluid/fluid_scheme_incompressible.f90
  src/krylov/pc_hsmg.f90
  src/scalar/scalar_scheme.f90
  src/source_terms/brinkman/PDE_filter.f90
  tests/reframe/src/minihemi.case.template
  tests/reframe/src/rayleigh.case.template
  tests/reframe/src/tgv.case.template
  tests/regression/cylinder/cylinder_part1.case
  tests/regression/cylinder/cylinder_part2.case
Labels: enhancement

#1883 Add type injection to wall models and point zones
  doc/pages/user-guide/extension.md
  doc/pages/user-guide/io.md
  src/les/les_model_fctry.f90
  src/mesh/point_zone.f90
  src/mesh/point_zone_fctry.f90
  src/simulation_components/simulation_component_fctry.f90
  src/source_terms/source_term_fctry.f90
  src/wall_models/wall_model.f90
  src/wall_models/wall_model_fctry.f90
Labels: enhancement

#1885 Add missing hip kernels
  src/math/bcknd/device/hip/hip_math.f90
  src/math/bcknd/device/hip/math.hip
  src/math/bcknd/device/hip/math_kernel.h
Labels: GPU

#1879 Chebyshev accelerated Schwarz
  src/.depends
  src/krylov/bcknd/cpu/cheby.f90
  src/krylov/bcknd/device/cheby_device.F90
  src/multigrid/phmg.f90
  src/multigrid/tree_amg_smoother.f90
Labels: enhancement

#1886 Add constructors from components to lambda_t and derivative_t
  src/.depends
  src/neko.f90
  src/simulation_components/derivative.f90
  src/simulation_components/field_writer.f90
  src/simulation_components/lambda2.f90
Labels: enhancement

#1897 Add monitor param for coarse grid
  src/krylov/pc_hsmg.f90
Labels: enhancement

#1899 Fix case file for turb_channel
  examples/turb_channel/turb_channel.case
Labels: case

#1892 Differential operator simcomps
  doc/pages/developer-guide/testing.md
  doc/pages/user-guide/simcomps.md
  examples/tgv/tgv.case
  src/.depends
  src/Makefile.am
  src/field/field_registry.f90
  src/neko.f90
  src/simulation_components/curl_simcomp.f90
  src/simulation_components/derivative_simcomp.f90
  src/simulation_components/divergence_simcomp.f90
  src/simulation_components/gradient_simcomp.f90
  src/simulation_components/simulation_component_fctry.f90
  src/simulation_components/vorticity.f90
  src/simulation_components/weak_grad.f90
  src/simulation_components/weak_gradient_simcomp.f90
Labels: enhancement, refactor

#1900 Update cylinder examples with curl simcomp
  examples/api/c/cylinder.case
  examples/api/pyneko/cylinder.case
  examples/cylinder/cylinder.case
Labels: case

#1904 Add missing documentation page to index
  doc/DoxygenLayout.xml
  doc/Makefile.am
  doc/pages/index.md
  doc/pages/user-guide.md
Labels: documentation

#1903 Fix bug in simcomp documentation
  doc/pages/user-guide/simcomps.md
Labels: bug, documentation

#1889 Add singleton for user access
  examples/TS_channel/TS_channel.f90
  examples/advecting_cone/advecting_cone.f90
  examples/cyl_boundary_layer/cyl_bl.f90
  examples/rayleigh_benard/rayleigh.f90
  examples/rayleigh_benard_cylinder/rayleigh.f90
  examples/scalar_mms/scalar_mms.f90
  examples/turb_channel/turb_channel.f90
  examples/turb_pipe/insitu_turb_pipe.f90
  examples/turb_pipe/turb_pipe.f90
  makeneko.in
  src/.depends
  src/Makefile.am
  src/case.f90
  src/common/user_access_singleton.f90
  src/neko.f90
  src/simulation.f90
  src/simulation_components/simcomp_executor.f90
  tests/reframe/src/rayleigh.f90
Labels: enhancement
