Repository ExtremeFLOW/neko, pull requests merged in 2025-09, with the labels that each got.

#2081 Fix parmetis type wrappers
  src/comm/parmetis.F90
Labels: bug, compilers, NAG

#2050 Change the definition of the elementwise_average les delta field
  src/les/les_model.f90
Labels: don't merge

#2084 Remove mean_sqr_field and related files
  configure.ac
  src/.depends
  src/Makefile.am
  src/field/mean_sqr_field.f90
  src/fluid/fluid_scheme_incompressible.f90
  src/fluid/mean_sqr_flow.f90
  src/io/fld_file.f90
  src/io/mean_sqr_flow_output.f90
  tests/unit/.gitignore
  tests/unit/Makefile.am
  tests/unit/mean_sqr_field/Makefile.in
  tests/unit/mean_sqr_field/mean_sqr_field_parallel.pf
  tests/unit/mean_sqr_field/mean_sqr_field_test
Labels: refactor

#2096 some typos in governing equations
  doc/pages/appendices/governing-equations.md
Labels: documentation

#2106 Update of fluid output file documentation; fixes #1982
  doc/pages/user-guide/io.md
Labels: documentation

#2107 Add copy to device in dirichlet_conditions
  examples/cyl_boundary_layer/cyl_bl.f90
  examples/lid/lid.f90
  examples/rayleigh_benard_cylinder/rayleigh.f90
Labels: bug

#2109 change json_extract_object to json_get in neko_api
  src/api/neko_api.f90
Labels: bug, API
